CHANGELOG.md
DEPENDENCIES
cx-portal-shared-components/package.json
cx-portal/package.json
package.json

The last merge into main for v1.3.0 was RC4. This PR contains the delta up to the finalization of v1.3.0.
Changes:
- update changelog (known knowns) and version

release: finalize v1.3.0

---

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md

Add pull request template.
To improve the quality of pull requests.
n/a

chore: add pull request template

---

cx-portal/src/features/apps/apiSlice.ts

An API endpoint URL has changed.
The changed API endpoint must be updated on frontend side to access that endpoint from now on.
No issue ref.

bugfix(apps): update changed endpoint url

---

CHANGELOG.md
cx-portal/src/assets/locales/de/servicerelease.json
cx-portal/src/assets/locales/en/servicerelease.json
cx-portal/src/components/pages/ServiceReleaseProcess/components/index.tsx
cx-portal/src/components/pages/ServiceReleaseProcess/index.tsx
cx-portal/src/components/shared/basic/ReleaseProcess/OfferTechnicalIntegration/index.tsx
cx-portal/src/components/shared/basic/ReleaseProcess/components/ReleaseProcessWrapper.tsx
cx-portal/src/features/serviceManagement/apiSlice.ts

Added technical integration step for service release process
To enhance service release process
Refs: CPLP-2616, CPLP-2617

feat(service release process): Added technical integration

---

cx-portal/src/assets/locales/de/main.json
cx-portal/src/assets/locales/en/main.json

Portal asset/locales (translation files) updated de & en
The current available descriptions/text messages stored in the locale files (de & en) did not perfectly fit to the actual user flow and generated confusion. Additionally the "de" locale file did still hold the english version of the respective text messages. Now, the german translation was added
n/a

change(app subscription): update locale files

---

CHANGELOG.md
cx-portal/src/assets/locales/de/main.json
cx-portal/src/assets/locales/en/main.json
cx-portal/src/components/overlays/UpdateCompanyRole/index.tsx
cx-portal/src/components/pages/CompanyRoleUpdate/index.tsx
cx-portal/src/features/companyRoles/companyRoleApiSlice.ts
cx-portal/src/features/companyRoles/slice.ts
cx-portal/src/features/store.ts

BL&API POST CompanyRole and Consent & Error/Success
Include the backend logic with frontend for Company Update
Related to CPLP-1534

feat(company role update): add backend update logic to update company roles

---

CHANGELOG.md
cx-portal/src/assets/locales/de/main.json
cx-portal/src/assets/locales/de/servicerelease.json
cx-portal/src/assets/locales/en/main.json
cx-portal/src/assets/locales/en/servicerelease.json
cx-portal/src/components/pages/AdminBoardDetail/BoardContentDetails.tsx
cx-portal/src/components/pages/AdminBoardDetail/components/BoardTechnicalUserSetup/index.tsx
cx-portal/src/components/pages/ServiceAdminBoardDetail/index.tsx
cx-portal/src/components/shared/basic/ReleaseProcess/components/CommonValidateAndPublish.tsx
cx-portal/src/features/adminBoard/serviceAdminBoardApiSlice.ts
cx-portal/src/features/appManagement/types.ts
cx-portal/src/features/apps/apiSlice.ts
cx-portal/src/features/serviceManagement/types.ts

Added tech user setup section to validate and publish and admin boards in both app and service release process.
To update app and service release process with tech user setup
Ref: 2620, 2621, 2624, 2625

feat(app and service release process): Added tech user setup section

---

sonar-project.properties

sonarcloud: prevent test files to cause duplications
test files cause duplications in sonarcloud analysis
n/a

chore(sonarcloud): prevent duplications due to test files

---

CHANGELOG.md
cx-portal/src/features/serviceProvider/serviceProviderApiSlice.ts

Change Endpoints as per backend
CPLP-2498

feat(service provider): change endpoints

---

cx-portal-shared-components/src/components/content/Cards/AboutCard.stories.tsx

change example data for about card
example data was confusing
n/a

fix(about-card): change example data

---

CHANGELOG.md
cx-portal/src/assets/locales/de/main.json
cx-portal/src/assets/locales/de/servicerelease.json
cx-portal/src/assets/locales/en/main.json
cx-portal/src/assets/locales/en/servicerelease.json
cx-portal/src/components/shared/basic/ReleaseProcess/ReleaseProcessSteps.scss
cx-portal/src/components/shared/basic/ReleaseProcess/components/CommonValidateAndPublish.tsx
cx-portal/src/features/appManagement/slice.ts

UI style updates to validate and publish to fix alignment
To enhance the look and feel of the application
ref: CPLP-2806

update(validate and publish): UI alignment fix

---

CHANGELOG.md
DEPENDENCIES
cx-portal-shared-components/package.json
cx-portal/package.json
package.json

merge main in dev for 1.5.0-RC1 version.
to wrap up release process for 1.5.0-RC1 version.
n/a

release(1.5.0-RC1): merge main in dev

---

CHANGELOG.md
cx-portal/src/components/pages/AppDetail/components/AppDetailHeader/index.tsx

Subscribe Button - wrong state fix
Disable the button if particular role not exists
CPLP-2816

fix(subscribe btn): fix subscribe button wrong state in appdetail

---

CHANGELOG.md
cx-portal/src/components/pages/ServiceReleaseProcess/components/index.tsx
cx-portal/src/components/shared/basic/ReleaseProcess/OfferPage/index.tsx
cx-portal/src/components/shared/basic/ReleaseProcess/components/ReleaseProcessWrapper.tsx

skip technical integration for consultancy service
Not required for consultancy service alone
Ref: CPLP-2622

feat(Service release process): skip technical integration

---

cx-portal/src/components/overlays/ActivateServiceSubscription/index.tsx
cx-portal/src/components/pages/AppSubscription/ActivateSubscriptionOverlay/index.tsx
cx-portal/src/components/shared/basic/Dailog/CustomDialogHeader.tsx

Activation Overlay UI changes
Improvements in UI
CPLP-2664

feat(activation overlay): ui changes

---

cx-portal/src/components/overlays/EnableIDP/EnableIDPContent.tsx
cx-portal/src/components/pages/SemanticHub/DownloadLink.tsx
cx-portal/src/components/pages/SemanticHub/ModelDetailDialog.tsx
cx-portal/src/components/pages/Translator/index.tsx

Veracode Bugs Fixes
To improve analytics
CPLP-2693

fix(veracode): bug fixes

---

cx-portal/src/components/pages/TechnicalUserDetails/TechnicalUserDetailsContent.tsx
cx-portal/src/components/shared/basic/KeyValueView/index.tsx

Technical User Details
UI enhancement
CPLP-2849

fix(technical user detail): ui fixes

---

CHANGELOG.md
cx-portal/src/components/pages/ServiceReleaseProcess/components/ServiceDetails.tsx
cx-portal/src/components/shared/basic/ReleaseProcess/components/ReleaseProcessWrapper.tsx

Because of cache issue, service release process steps are not working
Read 1st document from any type to avoid crash issue
Service release process steps not working
Service details page crash issue
NA

bugfix(service release process): service release process

---

CHANGELOG.md
cx-portal/src/components/pages/ServiceReleaseProcess/components/ServiceDetails.tsx

crash issue fix on click of in review service
Open "In Review" Service fails
NA

bugfix(service details): crash issue fix on click of in review service

---

CHANGELOG.md
cx-portal/src/components/pages/TechnicalUserDetails/TechnicalUserDetailsContent.tsx
cx-portal/src/components/shared/basic/ReleaseProcess/OfferPage/index.tsx
cx-portal/src/components/shared/basic/ReleaseProcess/OfferTechnicalIntegration/index.tsx

skip technical integration on offerpage load
To enhance the release process
Ref: CPLP-2622

update(Service release process): skip technical integration 

---

CHANGELOG.md
cx-portal/src/assets/locales/de/main.json
cx-portal/src/assets/locales/en/main.json
cx-portal/src/components/pages/AppOverview/AppOverview.scss
cx-portal/src/components/pages/AppOverview/ChangeImage.tsx
cx-portal/src/components/pages/AppOverview/Deactivate.tsx
cx-portal/src/components/pages/AppOverview/index.tsx
cx-portal/src/components/shared/basic/ReleaseProcess/components/ConnectorFormInputFieldImage.tsx
cx-portal/src/features/appManagement/apiSlice.ts

image change(sub menu) functionality added for active apps
Enhance
Ref: CPLP-1553, CPLP-1554, CPLP-2888

feat(App overview): image change functionality 

---

.github/workflows/release.yml
.github/workflows/release_candidate.yml
CHANGELOG.md
DEPENDENCIES
cx-portal-shared-components/README.md
cx-portal-shared-components/package.json
cx-portal/package.json
cx-portal/src/components/pages/ServiceReleaseProcess/components/ServiceDetails.tsx
cx-portal/src/components/shared/basic/ReleaseProcess/components/CommonValidateAndPublish.tsx
cx-portal/src/components/shared/templates/Subscription/SubscriptionElements.tsx
cx-portal/src/features/appSubscription/appSubscriptionApiSlice.ts
package.json

merge release branch in main for 1.5.0 version.
to wrap up release process for 1.5.0 version.
n/a

release(1.5.0): merge release in main

---

CHANGELOG.md
cx-portal/src/assets/locales/de/main.json
cx-portal/src/assets/locales/en/main.json
cx-portal/src/components/overlays/EditUsecase/index.tsx
cx-portal/src/components/overlays/EditUsecase/style.scss
cx-portal/src/components/pages/TechnicalUserDetails/TechnicalUserDetailsContent.tsx
cx-portal/src/components/pages/UsecaseParticipation/UsecaseParticipation.scss
cx-portal/src/components/pages/UsecaseParticipation/index.tsx
cx-portal/src/services/AccessService.tsx
cx-portal/src/types/Config.tsx
cx-portal/src/types/Constants.ts

New page of Usecase Participation
To get the details of usecase and edit the usecase
CPLP-2851

feat(use case): add support for use cases

---

scripts/legal-notice.sh

Fixed wrong path
Build was breaking due to wrong path.
n/a

bugfix(legal notice): fixed path

---

CHANGELOG.md
src/components/shared/frame/SlidingMainHeader/SlidingMainHeader.scss

when switching the portal width screens get rendering issues fixed
component width issue fix
NA

bugfix(home carousel): responsiveness

---

CHANGELOG.md
src/assets/locales/de/main.json
src/assets/locales/en/main.json
src/components/pages/AppSubscription/AppSubscriptionDetailOverlay/index.tsx
src/features/appSubscription/appSubscriptionApiSlice.ts

Add edit url functionality in app subscription detail overlay
To provide update tenant uel functionality
CPLP-2843

feat(app subscription): add tenant url indetail overlay

---

CHANGELOG.md
src/assets/locales/de/main.json
src/assets/locales/en/main.json
src/components/pages/AppSubscription/AppSubscriptionDetailOverlay/index.tsx
src/features/appSubscription/appSubscriptionApiSlice.ts

Reverts eclipse-tractusx/portal-frontend#96
The build broke after merging the PR

Revert "feat(app subscription): add tenant url indetail overlay"

---

CHANGELOG.md
src/components/shared/basic/ReleaseProcess/AppMarketCard/index.tsx
src/features/appManagement/apiSlice.ts

App Release Process: updated language endpoint changed structure
As api structure is changed/updated from backend
Ref: CPLP-1305

update(App Release Process): updated language endpoint

---

src/components/pages/AppOverview/AppOverview.scss
src/components/pages/AppOverview/ChangeImage.tsx
src/components/pages/AppOverview/Deactivate.tsx

update(app overview): feedback issues resolved 
Enhance
Ref: CPLP-2812, 1553

update(app overview): feedback fixes

---

README.md
package.json
yarn.lock

Fixed service detail view
Page was broken when some values where undefined
JIRA: CPLP-2914

bugfix(service detail): fix display for undefined values

---

CHANGELOG.md
src/components/overlays/UpdateCompanyRole/index.tsx

Change the payload of updating company role as per backend logic
To update the company roles
JIRA: CPLP-2729

feat(update company role): chnage the post request payload

---

DEPENDENCIES
package.json
yarn.lock

Upgrade library to include card style fix
Card style fix implemented in library
JIRA: CPLP-2807

chore(components): upgrade library

---

CHANGELOG.md
src/assets/locales/de/notification.json
src/assets/locales/en/notification.json
src/components/pages/NotificationCenter/index.tsx
src/components/shared/frame/FramedSelector/FramedSelector.scss
src/components/shared/frame/FramedSelector/index.tsx
src/components/shared/frame/SectionHeader/SectionHeader.scss
src/components/shared/frame/SectionHeader/index.tsx

Change header section and add help section link as well.
Change filter UI
more user friendly 
NA

updates(notification): update header and filter ui

---

CHANGELOG.md
src/assets/locales/de/main.json
src/assets/locales/en/main.json
src/components/pages/DataSpace/UseCase.scss
src/components/pages/DataSpace/index.tsx
src/components/pages/UseCase/index.tsx
src/components/shared/templates/StaticTemplateResponsive/Cards/ImageVideoWrapper.tsx
src/components/shared/templates/StaticTemplateResponsive/Cards/LinkButtonGrid.tsx
src/components/shared/templates/StaticTemplateResponsive/Cards/RenderImage.tsx
src/components/shared/templates/StaticTemplateResponsive/StaticTemplate.scss
src/components/shared/templates/StaticTemplateResponsive/StaticTypes.ts
src/components/shared/templates/StaticTemplateResponsive/index.tsx
src/services/CommonService.ts
src/types/Config.tsx
src/types/Constants.ts

new static page - data space. update navigation object in use case and company roles
new page
NA

feat(static page): new static page

---

src/assets/locales/de/main.json
src/assets/locales/en/main.json
src/components/overlays/UpdateCertificate/index.tsx
src/components/pages/CertificateCredentials/CertificateCredentials.scss
src/components/pages/CertificateCredentials/CertificateElements.tsx
src/components/pages/CertificateCredentials/index.tsx
src/components/pages/UsecaseParticipation/UsecaseParticipation.scss
src/components/pages/UsecaseParticipation/index.tsx
src/components/shared/basic/CertificateCard/index.tsx
src/features/certification/certificationApiSlice.tsx
src/types/Config.tsx
src/types/Constants.ts

Business Logic for upload certificate
CPLP-2926

feat(certificate): added overlay business logic

---

CHANGELOG.md
src/assets/locales/de/main.json
src/assets/locales/en/main.json
src/components/pages/AdminCredential/AdminCredential.scss
src/components/pages/AdminCredential/AdminCredentialElements.tsx
src/components/pages/AdminCredential/index.tsx
src/features/certification/certificationApiSlice.tsx
src/features/usecase/usecaseApiSlice.ts
src/types/Config.tsx
src/types/Constants.ts

Added new Page for Certificate Admin Board
This page is created under User Menu to accept/decline the certificate
N/A

feat(certificate admin board): add new page and created ui

---

CHANGELOG.md
src/assets/locales/de/main.json
src/assets/locales/en/main.json
src/components/pages/EdcConnector/AddConnectorOverlay/components/ConnectorInsertForm.tsx
src/components/pages/EdcConnector/AddConnectorOverlay/index.tsx
src/components/pages/EdcConnector/index.tsx
src/features/connector/connectorApiSlice.ts

Create Connectors
- fetch offer subscription in managed connectors
- create managed api end point update
- update created managed api body with subscriptionId
change request
NA

updates(connector): managed connectors

---

CHANGELOG.md
DEPENDENCIES
src/components/shared/templates/StageSubNavigation/index.tsx
src/components/shared/templates/StaticTemplateResponsive/Cards/TextImageSideBySideWithSections.tsx
src/components/shared/templates/Templates.scss

style fix stage sub navigation header. fix responsive issue in new template
UI is broken
NA

bugfix(static pages): stage subnavigation & responsiveness

---

CHANGELOG.md
DEPENDENCIES
src/features/connector/connectorApiSlice.ts

update create connectors end point
change request
NA

update(connectors): update end point

---

src/components/pages/AppDetail/AppDetailContentDetails.tsx
src/components/shared/frame/SearchOverlay/Search.scss
src/components/shared/frame/SearchOverlay/SearchResultSection/search-result-section.scss
src/components/shared/frame/SearchOverlay/index.tsx
src/components/shared/templates/StageSubNavigation/index.tsx
src/components/shared/templates/StaticTemplateResponsive/Cards/TextImageCenterAligned.tsx
src/components/shared/templates/StaticTemplateResponsive/Cards/TextImageSideBySide.tsx
src/components/shared/templates/StaticTemplateResponsive/Cards/TextImageSideBySideWithSections.tsx
src/components/shared/templates/StaticTemplateResponsive/StaticTemplate.scss
src/components/shared/templates/Templates.scss

remove inline back button from overlay. stage navigation header width issue fix
back action is misleading
NA

updates(search): remove back and fix responsiveness

---

.sonarcloud.properties

exclude locales from copy paste detection / duplication check
https://github.com/eclipse-tractusx/portal-frontend/pull/141
https://github.com/eclipse-tractusx/portal-frontend/pull/146
n/a

chore(sonarcloud): exclude locales from duplication check

---

src/assets/locales/de/main.json
src/assets/locales/en/main.json
src/components/pages/TechnicalUserManagement/TechnicalUserTable.tsx

add new columns. Type, owner and offer information to the table
new values from api
NA

updates(tech user): update tech user table with new contents

---

CHANGELOG.md
package.json
src/components/shared/templates/Subscription/SubscriptionElements.tsx

Bump version
To have the latest package version
N/A

release: bump version for v1.6.0-RC3

---

DEPENDENCIES
package.json
yarn.lock

Updated shared component version
To deployed latest changes
N/A

chore(version): increase shared component version

---

src/components/pages/AppOverview/AppOverview.scss

Card Responsive Changes
UI enhancement
N/A

feat(card responsive): made card responsive in usermanagemtn

---

src/components/pages/AdminCredential/AdminCredentialElements.tsx

SSI Credential UI and status fix
UI enhancement
N/A

feat(ssi credential): add status for pending state only

---

public/index.html
scripts/inject-dynamic-env.sh
src/assets/locales/de/main.json
src/assets/locales/en/main.json
src/components/pages/EdcConnector/ConfigurationDetailsOverlay.tsx
src/components/pages/EdcConnector/EdcConnector.scss
src/components/pages/EdcConnector/index.tsx
src/components/shared/frame/PictureWithText/index.tsx
src/components/shared/templates/Subscription/SubscriptionElements.tsx
src/features/connector/connectorApiSlice.ts
src/services/EnvironmentService.ts

update title and get help link in connector page
change request
NA

updates(connector): update content and help link

---

package.json

Updated package version of shared component
To deploy the updated code
N/A

"chore(version): increase shared component version"

---

CHANGELOG.md
package.json

Bump the version and update the change log for release v1.6.0-RC4
To have the correct version in the release branch
N/A

release: bump version for v1.6.0-RC4

---

src/types/Config.tsx

Added roles for admin credential
Want to show this for particular roles users only
n/a

bugfix(admin credentials): added roles for admin credential

---

CHANGELOG.md
package.json
public/index.html
scripts/inject-dynamic-env.sh
src/assets/locales/de/main.json
src/assets/locales/en/main.json
src/components/pages/AdminCredential/AdminCredentialElements.tsx
src/components/pages/AppOverview/AppOverview.scss
src/components/pages/EdcConnector/ConfigurationDetailsOverlay.tsx
src/components/pages/EdcConnector/EdcConnector.scss
src/components/pages/EdcConnector/index.tsx
src/components/shared/frame/PictureWithText/index.tsx
src/features/connector/connectorApiSlice.ts
src/services/EnvironmentService.ts
src/types/Config.tsx

Merge release into main
To have the latest changes available in main
N/A

release(1.6.0-RC4): merge release into main

---

CHANGELOG.md
package.json
public/index.html
scripts/inject-dynamic-env.sh
src/assets/locales/de/main.json
src/assets/locales/en/main.json
src/components/pages/AdminCredential/AdminCredentialElements.tsx
src/components/pages/AppOverview/AppOverview.scss
src/components/pages/EdcConnector/ConfigurationDetailsOverlay.tsx
src/components/pages/EdcConnector/EdcConnector.scss
src/components/pages/EdcConnector/index.tsx
src/components/shared/frame/PictureWithText/index.tsx
src/features/connector/connectorApiSlice.ts
src/services/EnvironmentService.ts
src/types/Config.tsx

Merge main into dev
To have the latest changes available in dev
N/A

release(1.6.0-RC4): merge main to dev

---

src/types/Config.tsx
src/types/Constants.ts

Admin Credential Role change
Roles added as per logic
n/a

fix(admin credential): role change

---

src/assets/locales/de/main.json
src/assets/locales/en/main.json
src/components/overlays/AddTechnicalUser/TechnicalUserAddForm.scss
src/components/overlays/AddTechnicalUser/TechnicalUserAddForm.tsx
src/components/overlays/AddTechnicalUser/index.tsx
src/features/admin/serviceApiSlice.ts

UI changes and added data
UI enhancement and add data from API
n/a

feat(technical integration): ui enhancement

---

src/components/overlays/AddTechnicalUser/TechnicalUserAddForm.tsx

Add hyphen if no role description is present
User friendly
n/a

feat(technical user): add hyphen if no description

---

src/components/shared/basic/ReleaseProcess/components/CommonContractAndConsent.tsx
src/features/store.ts

Fixed console errors related to app release process.
to remove errors on console
Ref: CPLP-2311

fix(app release process): fixed console errors

---

CHANGELOG.md
package.json

update change log for v1.6.0-RC5
bump version for version v1.6.0-RC5
To have a new version for the release
N/A

release: update changelog for v1.6.0-RC5

---

src/components/pages/AppMarketplace/components/AppListSection/index.tsx

Card Clickable affecting Favorite icon in marketplace
User Friendly
n/a

Fix(card): card clickable fix

---

src/components/pages/AdminCredential/AdminCredentialElements.tsx

Fix filters in ssi credential and cleanup
Filter are not working
n/a

fix(ssi credntial): fix filters

---

src/features/admin/serviceApiSlice.ts

Add language support in api call
To support Multilanguage
n/a

feat(service account): add lang support in api call

---

src/components/pages/ServiceMarketplaceDetail/components/MarketplaceHeader/MarketplaceHeader.scss

Service detail header ui fixes
UI enhancement
n/a

fix(service detail): ui fix

---

.eslintrc.json
DEPENDENCIES
package.json
yarn.lock

Upgrade dependencies.
Upgrading dependencies to the latest versions is a routine process.
ref. Jira CPLP2995

bugfix(deps): fix dependabot findings

---

DEPENDENCIES
src/components/shared/basic/ReleaseProcess/OfferCard/index.tsx

Fixed missing information regarding provider details in service release process
To include the missing provider details
Ref: TEST-1263

fix(service release process): fixed missing information

---

src/assets/locales/de/main.json
src/assets/locales/en/main.json
src/components/overlays/DeleteTechnicalUser/index.tsx
src/features/admin/serviceApiSlice.ts

show error message if api call fails to delete tech user
no error message appears if api fails
NA

updates(tech user): show error message

---

.tractusx
CHANGELOG.md
package.json
src/@types/i18next.d.ts
src/@types/react-slick.d.ts
src/components/overlays/IDPDelete/idpdelete.scss
src/components/overlays/IDPDelete/index.tsx
src/components/overlays/IDPStatusChange/index.tsx
src/components/overlays/IDPTestRun/index.tsx
src/components/overlays/UpdateCompanyRole/style.scss
src/components/shared/basic/CertificateCard/style.scss
src/components/shared/basic/ReleaseProcess/components/ComponentStyles.scss
src/components/shared/basic/UserRoles/UserRole.scss
src/utils/downloadUtils.ts

- bump version
- update changelog
- add file headers https://github.com/eclipse-tractusx/portal-frontend/issues/218
- remove the following two empty files:
src/components/pages/Home/components/StageSection/stage-section.scss
src/components/pages/UserManagement/StageSection/stage-section.scss
to prepare the release branch for the latest release
N/A

release: finalize v1.6.0-RC7 

---

src/components/pages/AppDetail/AppDetailContentDetails.tsx
src/components/shared/basic/CertificateCard/index.tsx

White page fix
To fix errors
n/a

fix(credential): credential white page fix

---

src/components/pages/Organization/index.tsx
src/components/pages/UserManagement/AppArea/index.tsx
src/features/apps/apiSlice.ts
src/features/apps/mapper.ts

subscription-status Endpoint Changes
Connect with new api endpoints
n/a

fix(endpoint changes): change subscription-status api endpoint

---

CHANGELOG.md
DEPENDENCIES
package.json
src/assets/locales/de/main.json
src/assets/locales/en/main.json
src/components/pages/AppDetail/AppDetailContentDetails.tsx
src/components/pages/Organization/index.tsx
src/components/pages/UserManagement/AppArea/index.tsx
src/components/shared/basic/CertificateCard/index.tsx
src/features/apps/apiSlice.ts
src/features/apps/mapper.ts
yarn.lock

Merge release branch  for v1.6.0-RC8 into main
to wrap up release process
N/A

release(1.6.0-RC8): merge release into main

---

CHANGELOG.md
DEPENDENCIES
package.json
src/assets/locales/de/main.json
src/assets/locales/en/main.json
src/components/pages/AppDetail/AppDetailContentDetails.tsx
src/components/pages/Organization/index.tsx
src/components/pages/UserManagement/AppArea/index.tsx
src/components/shared/basic/CertificateCard/index.tsx
src/features/apps/apiSlice.ts
src/features/apps/mapper.ts
yarn.lock

merge main in dev for 1.6.0-RC8 version.
to wrap up release process for 1.6.0-RC8 version.
n/a

release(1.6.0-RC8): merge main in dev

---

CHANGELOG.md
src/components/pages/Organization/index.tsx
src/features/apps/apiSlice.ts
src/features/apps/mapper.ts

switch endpoint used to display app subscriptions
use new url
NA

updates(my organization): update end point

---

src/assets/locales/de/main.json
src/assets/locales/en/main.json
src/components/pages/AppOverview/AddRoles.tsx
src/components/pages/AppOverview/AddRolesOverlay.tsx
src/components/pages/AppOverview/AppOverview.scss
src/components/pages/AppOverview/AppOverviewList.tsx
src/components/pages/AppOverview/ChangeDescription.tsx
src/components/pages/AppOverview/index.tsx
src/features/appManagement/apiSlice.ts
src/types/Config.tsx
src/types/Constants.ts

Add roles functionality is added to app overview active apps
To enhance active apps functionality
Ref: CPLP-1563, CPLP-1564

feat(app overview): implemented add roles

---

CHANGELOG.md
NOTICE.md
package.json
public/cx-logo-gray.svg.license
public/cx-logo-text.svg.license
public/cx-logo.svg.license
public/orange-background-full.svg.license
public/orange-background-head.svg.license
src/assets/logo/cx-logo-short.svg.license

merge main in dev for 1.6.0 version.
to wrap up release process for 1.6.0 version.
n/a

release(1.6.0): merge main in dev

---

public/user-bulk-load-ownIdp.csv
src/assets/locales/de/main.json
src/assets/locales/en/main.json
src/components/overlays/AddMultipleUser/index.tsx
src/features/appManagement/userManagementApiSlice.ts

User bulk upload ownidp
Add functionality for ownidp scenario
n/a

feat(user bulk upload): bulk upload ownidp

---

src/components/pages/AppSubscription/ActivateSubscriptionOverlay/index.tsx
src/components/shared/templates/Subscription/SubscriptionElements.tsx
src/types/Patterns.ts

Remove calling unnecessary API and add validation for url in subscription
UI improvements
n/a

fix(app subscription): fix api error and validation

---

CHANGELOG.md
src/assets/locales/de/main.json
src/assets/locales/en/main.json
src/components/pages/TechnicalUserManagement/TechnicalUserTable.tsx
src/features/admin/serviceApiSlice.ts
src/types/Patterns.test.ts
src/types/Patterns.ts

enable search by client id and filter options with owned and manged
change request
NA

updates(tech user): enable search and filter option

---

CHANGELOG.md
DEPENDENCIES
src/assets/locales/de/main.json
src/assets/locales/en/main.json
src/components/pages/TechnicalUserDetails/TechnicalUserDetailsContent.tsx
src/features/admin/serviceApiSlice.ts

add reset credential button and respective api integration
enable new functionality
NA

feat(technical-user-details): enable credential reset

---

CHANGELOG.md
DEPENDENCIES
src/components/overlays/AddMultipleUser/index.tsx
src/components/pages/AppOverview/index.tsx
src/components/pages/AppOverviewNew/index.tsx
src/features/apps/apiSlice.ts

Fixed page break in app management and app overview
Due to change in the api response structure
Ref: CPLP-3234

bugfix(app management): fix page break

---

CHANGELOG.md
src/components/overlays/InviteForm/InviteForm.scss

align loader gif to the center of the overlay.
loader gif is mis aligned
NA

bugfix(invite business partner): fix loader position

---

CHANGELOG.md
DEPENDENCIES
src/assets/locales/de/main.json
src/assets/locales/en/main.json
src/components/pages/MyAccount/index.tsx

Show success message on click of copy to clip board
Missing User Feedback on "Copy token to clipboard"
NA

bugfix(account): show message

---

CHANGELOG.md
DEPENDENCIES
src/components/shared/basic/ReleaseProcess/components/CommonValidateAndPublish.tsx

fixed validate and publish image load issue
Image was not displayed
Ref: CPLP-3166

bugfix(app release process): fix image load

---

CHANGELOG.md
DEPENDENCIES
src/components/shared/templates/Subscription/SubscriptionElements.tsx

activate button showing service activation screen instead of app activation
wrong overlay being shown on activation
NA

fix(app subscription): change activation overlay

---

package.json
src/components/pages/AppOverview/AddRoles.tsx
src/components/pages/AppOverview/AddRolesOverlay.tsx

Roles feedback changes
To enhance
Ref: CPLP-1563

update(roles): ui styles update

---

CHANGELOG.md
src/components/pages/ServiceReleaseProcess/components/ServiceListOverview.tsx
src/components/shared/basic/ReleaseProcess/AppPage/index.tsx
src/features/serviceManagement/apiSlice.ts

clearing fields while registering new service and update service URL
Form to be empty for new service
Ref: CPLP-3249, CPLP-2821

bugfix(service release process): clear data for new service

---

src/components/overlays/AddMultipleUser/index.tsx
src/components/overlays/UpdateCertificate/index.tsx
src/features/admin/idpApiSlice.ts

Fixed changes that made the build pipeline break
A previous PR introduces changes that broke the build. We fix it with this PR
n/a

fix(build): fix breaking build

---

CHANGELOG.md
DEPENDENCIES
src/assets/locales/de/main.json
src/assets/locales/de/servicerelease.json
src/assets/locales/en/main.json
src/assets/locales/en/servicerelease.json
src/components/pages/ServiceAdminBoardDetail/index.tsx
src/components/pages/ServiceMarketplace/RecommendedServices.tsx
src/components/pages/ServiceMarketplace/ServicesElements.tsx
src/components/pages/ServiceMarketplace/index.tsx
src/components/pages/ServiceMarketplaceDetail/components/MarketplaceHeader/index.tsx
src/components/pages/ServiceReleaseProcess/components/ServiceDetails.tsx
src/components/pages/Test/index.form.tsx
src/components/shared/basic/ReleaseProcess/OfferTechnicalIntegration/index.tsx
src/components/shared/basic/ReleaseProcess/OfferValidateAndPublish/index.tsx
src/features/serviceManagement/apiSlice.ts
src/features/serviceMarketplace/serviceApiSlice.ts
src/services/LogService.ts

Corrected consultancy services naming and also removed hardcoded info related to consultancy
To align with BE response
Ref: CPLP-3248

bugfix(services): consultancy name change

---

CHANGELOG.md
DEPENDENCIES
src/features/apps/mapper.ts

Fixed image display for app overview cards
Image was not displayed
Ref: CPLP-3300

bugfix(app overview): image fix for app overview

---

CHANGELOG.md
src/components/pages/AppOverview/AddRoles.tsx
src/components/pages/IDPManagement/IDPList.tsx
src/components/pages/SemanticHub/ModelTable.tsx

update the props value the new name
migration to v6 effect
NA

updates(table): data grid migrate related changes

---

DEPENDENCIES
package.json
src/components/pages/AppOverview/AddRoles.tsx
src/components/pages/IDPManagement/IDPList.tsx
src/components/pages/SemanticHub/ModelTable.tsx
yarn.lock

Fix currently broken build
Previous PR #295 resulted in a broken build pipeline. This PR is to fix that and make the pipeline run again.

bugfix(build): fix broken build

---

CHANGELOG.md
DEPENDENCIES
src/assets/locales/de/main.json
src/assets/locales/en/main.json
src/components/shared/basic/ReleaseProcess/AppPage/index.tsx

fixed validation for contact field in app page
To enhance validation
Ref: CPLP-3304

bugfix(app page): contact validation fix

---

.eslintrc.json
CHANGELOG.md
DEPENDENCIES
src/components/pages/EdcConnector/index.tsx
src/components/shared/basic/ReleaseProcess/components/CommonContractAndConsent.tsx
src/features/admin/userDeprecated/actions.ts

Fixing ban type linters as instead of empty object define unknown
new linter rule
n/a

feat(linters): fixed ban types linters

---

src/services/CommonService.ts

add new object type to the company roles
crash issue
NA

bugfix(static templates): fix build issue

---

CHANGELOG.md
src/assets/locales/de/main.json
src/assets/locales/en/main.json
src/components/overlays/AddusersIDP/index.tsx
src/components/pages/TechnicalUserDetails/TechnicalUserDetailsContent.tsx
src/components/shared/basic/KeyValueView/index.tsx
src/features/admin/serviceApiSlice.ts

Add connected object table in technical user detail
Add page responsiveness
UI Enhancement
n/a

feat(technical user): add connected object table and made page responsive

---

CHANGELOG.md
src/components/shared/basic/ReleaseProcess/AppPage/index.tsx

Fixed salesManagerId null error
for navigating to app release process next steps
Ref: CPLP-3213

bugfix(app page): salesManagerId error fix

---

DEPENDENCIES
package.json
yarn.lock

for @babel/traverse
CVE-2023-45133

fix(vulnerability): set resolution

---

src/components/pages/Admin/components/RegistrationRequests/registrationTableColumns.tsx
src/components/pages/NotificationCenter/NotificationItem.tsx
src/components/shared/basic/ReleaseProcess/components/CommonContractAndConsent.tsx
src/components/shared/templates/Subscription/SubscriptionElements.tsx

Fix linter findings
PR checks were failing because of issues.
n/a

fix(linter): fix findings

---

CHANGELOG.md
package.json

update changelog for v1.7.0-RC2
bump version for v1.7.0-RC2
to have the latest version available

release: bump version for v1.7.0-RC2

---

src/assets/locales/de/idp.json
src/assets/locales/en/idp.json
src/components/overlays/AddIDP/index.tsx
src/components/overlays/EnableIDP/index.tsx
src/components/overlays/UpdateIDP/index.tsx

Added error state in overlays
Remove toast message with error state in overlays
n/a

feat(idp): added error state in overlays

---

src/components/overlays/IDPDelete/index.tsx
src/components/overlays/IDPStatusChange/index.tsx
src/components/pages/EdcConnector/ConfigurationDetailsOverlay.tsx
src/components/pages/Organization/AppSubscriptions.tsx
src/components/shared/frame/AppPermissions/index.tsx
src/components/shared/frame/Header/index.tsx

Sonar cloud  one keyboard listener fixes
Code quality improvements
n/a

fix(sonar bugs): fixed sonar bugs errors

---

CHANGELOG.md
src/components/pages/AppDetail/components/AppDetailHeader/AppDetailHeader.scss
src/components/pages/AppDetail/components/AppDetailHeader/index.tsx

App detail header UI changes
UI improvements
n/a

updates(app detail): ui changes

---

CHANGELOG.md
DEPENDENCIES
src/components/pages/AppOverview/AddRolesOverlay.tsx
src/components/shared/basic/ReleaseProcess/TechnicalIntegration/index.tsx

Fixed error message deletion upon deleting of csv file in technical integration
to display error message properly
Ref: CPLP-3490

bugfix(technical integration): error message fix

---

CHANGELOG.md
DEPENDENCIES
src/components/pages/AdminCredential/AdminCredential.scss
src/components/pages/AdminCredential/AdminCredentialElements.tsx
src/components/shared/basic/ReleaseProcess/components/CommonContractAndConsent.tsx

Add loading element to action buttons
UI Enhancement
n/a

feat(admin credential): add loading element to action buttons

---

CHANGELOG.md
src/components/pages/TechnicalUserDetails/TechnicalUserDetailsContent.tsx

fix crash issue in tech user details page
application is crashed
NA

bugfix(techuser): fix crash issue

---

CHANGELOG.md
src/assets/locales/de/main.json
src/assets/locales/en/main.json
src/components/pages/UsecaseParticipation/UsecaseParticipation.scss
src/components/pages/UsecaseParticipation/index.tsx
src/components/shared/basic/ReleaseProcess/components/CommonContractAndConsent.tsx

Document Icon Handling
UI Enhancement
n/a

feat(usecase): document icon handling

---

CHANGELOG.md
src/components/pages/AdminCredential/AdminCredential.scss

Document Hover effect in admin credential listing
UI Improvements
n/a

feat(admin credential): document hover effect

---

CHANGELOG.md
DEPENDENCIES
src/components/pages/AppSubscription/AppSubscriptionDetailOverlay/index.tsx
src/components/shared/basic/ReleaseProcess/components/CommonContractAndConsent.tsx
src/components/shared/templates/Subscription/SubscriptionElements.tsx
src/features/appSubscription/appSubscriptionApiSlice.ts

App and Service subscription logic update
As per backend API response there were logic updates in FE
n/a

feat(app and service): update subscription logic

---

.github/workflows/trivy-dev.yml
.github/workflows/trivy.yml
CHANGELOG.md
DEPENDENCIES
package.json
src/assets/locales/de/main.json
src/assets/locales/de/servicerelease.json
src/assets/locales/en/main.json
src/assets/locales/en/servicerelease.json
src/components/overlays/ActivateServiceSubscription/index.tsx
src/components/pages/AdminCredential/AdminCredential.scss
src/components/pages/AdminCredential/AdminCredentialElements.tsx
src/components/pages/AppOverview/AddRolesOverlay.tsx
src/components/pages/AppOverview/ChangeDocuments.tsx
src/components/pages/AppSubscription/AppSubscriptionDetailOverlay/index.tsx
src/components/pages/TechnicalUserDetails/TechnicalUserDetailsContent.tsx
src/components/pages/UsecaseParticipation/UsecaseParticipation.scss
src/components/pages/UsecaseParticipation/index.tsx
src/components/shared/basic/ReleaseProcess/TechnicalIntegration/index.tsx
src/components/shared/basic/ReleaseProcess/components/CommonContractAndConsent.tsx
src/components/shared/templates/Subscription/SubscriptionElements.tsx
src/features/appManagement/apiSlice.ts
src/features/appSubscription/appSubscriptionApiSlice.ts
yarn.lock

Merge all related release changes to main
To have the latest changes available in main
N/A

release(1.7.0-RC4): merge release into main

---

.github/workflows/trivy-dev.yml
.github/workflows/trivy.yml
CHANGELOG.md
DEPENDENCIES
package.json
src/assets/locales/de/main.json
src/assets/locales/de/servicerelease.json
src/assets/locales/en/main.json
src/assets/locales/en/servicerelease.json
src/components/overlays/ActivateServiceSubscription/index.tsx
src/components/pages/AdminCredential/AdminCredentialElements.tsx
src/components/pages/AppOverview/AddRolesOverlay.tsx
src/components/pages/AppOverview/ChangeDocuments.tsx
src/components/pages/AppSubscription/AppSubscriptionDetailOverlay/index.tsx
src/components/pages/UsecaseParticipation/UsecaseParticipation.scss
src/components/pages/UsecaseParticipation/index.tsx
src/components/shared/basic/ReleaseProcess/TechnicalIntegration/index.tsx
src/components/shared/basic/ReleaseProcess/components/CommonContractAndConsent.tsx
src/components/shared/templates/Subscription/SubscriptionElements.tsx
src/features/appManagement/apiSlice.ts
src/features/appSubscription/appSubscriptionApiSlice.ts
yarn.lock

Merge the latest changes from main to dev
To have the latest changes available in dev
N/A

release(1.7.0-RC4): merge main to dev

---

src/components/shared/templates/StaticTemplateResponsive/Cards/TextImageSideBySideWithSections.tsx
src/components/shared/templates/StaticTemplateResponsive/Cards/TitleDescriptionAndSectionlink.tsx

align templates according to new template requirement
NA
NA

updates(static page): fix alignment problems

---

CHANGELOG.md
src/assets/locales/de/main.json
src/assets/locales/en/main.json
src/components/overlays/AddAppUserRoles/AddAppUserRoles.scss
src/components/overlays/AddAppUserRoles/index.tsx

Updated app access management flow
NA
Ref: CPLP-3077

update(user management): update roles 

---

.eslintrc.json
CHANGELOG.md
DEPENDENCIES
src/components/overlays/AddBPN/index.tsx
src/features/apps/marketplaceDeprecated/slice.ts

enable eslint rule - dot-notations
improve code quality
NA

updates(eslint): enable dot-notations rule

---

.eslintrc.json
CHANGELOG.md
src/hooks/useFormValidation.ts
src/utils/HttpClient.ts

enable no-inferrable-types rule
improve code quality
NA

updates(eslint): enable no-inferrable-types rule

---

.eslintrc.json
CHANGELOG.md
src/utils/HttpClient.ts

enable prefer-readonly rule
improve code quality
NA

updates(eslint): enable prefer-readonly rule

---

.dockerignore
.gitignore
package.json

add legal info (LICENSE NOTICE.md DEPENDENCIES SECURITY.md) at build
https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-05
https://github.com/eclipse-tractusx/portal-frontend/issues/382

build(trg-7.05): add legal info at build

---

src/components/pages/Home/Home.scss
src/components/pages/Home/components/BusinessApplicationsSection/index.tsx

fixed home page break due to my business applications
Due to my business applications
Ref: CPLP-3544

fix(home): fix white screen at home page

---

.eslintrc.json
CHANGELOG.md
src/react-app-env.d.ts

enable triple-slash-reference rule
improve code quality
NA

updates(eslint): enable triple-slash-reference rule

---

.dockerignore
.github/workflows/pullRequest-lint.yaml
.gitignore
CHANGELOG.md
package.json
src/assets/notice/legal-notice.json
src/components/pages/Home/Home.scss
src/components/pages/Home/components/BusinessApplicationsSection/index.tsx

Merge all related release changes to main
To have the latest changes available in main
N/A

release(1.7.0): merge release into main

---

.dockerignore
.github/workflows/pullRequest-lint.yaml
.gitignore
CHANGELOG.md
package.json
src/components/pages/Home/Home.scss
src/components/pages/Home/components/BusinessApplicationsSection/index.tsx

Merge the latest changes from main to dev
To have the latest changes available in dev
N/A

release(1.7.0): merge main to dev

---

CHANGELOG.md
DEPENDENCIES
src/components/pages/AppDetail/components/AppDetailDocuments/index.tsx
src/components/shared/frame/Header/index.tsx
src/components/shared/frame/UserInfo/index.tsx

Fixed error message to display when data is not available
No data message should not appear when data is available
Ref: CPLP-3547

fix: error message fix

---

CHANGELOG.md
src/components/shared/basic/ReleaseProcess/components/ReleaseProcessWrapper.tsx

fixed automatic upscrolling in form pages
To enhance UI
Ref: CPLP-3559

fix(release process): automatic up scrolling fix

---

DEPENDENCIES
src/assets/locales/de/servicerelease.json
src/assets/locales/en/servicerelease.json
src/components/overlays/ActivateServiceSubscription/index.tsx
src/components/overlays/ActivateServiceSubscription/style.scss

Service Subscription Activation Overlay several updates
UI Enhancements
n/a

fix(service subscription): add copy icon to static table

---

package.json

Upgrade Shared component version
To update with latest changes
n/a

feat(package.json): upgrade shared component version

---

.github/workflows/release-release_candidate.yml
.github/workflows/release.yml

add additional image tags of type semver
https://github.com/eclipse-tractusx/portal-frontend/issues/381

build(release): add additional image tags of type semver

---

CHANGELOG.md
DEPENDENCIES
package.json
src/components/pages/Home/components/MenuInfo/menu-info.scss
src/components/shared/frame/UserInfo/UserInfo.tsx
src/components/shared/frame/UserInfo/index.tsx
yarn.lock

do not show new menu overlay when profile/user menu is visible
two overlays are appearing
NA

fix(hamburger menu): update hamburger style

---

CHANGELOG.md
src/assets/locales/de/main.json
src/assets/locales/en/main.json
src/components/pages/AppOverview/AddRolesOverlay.tsx
src/components/shared/basic/ReleaseProcess/TechnicalIntegration/index.tsx

Fixed help link, funky character display and the success message display in user role upload
To display valid/proper data
Ref: CPLP-3473

fix(technical integration): role upload findings

---

src/components/shared/frame/UserList/index.tsx

Fix page load issue
Error is arising due to change in backend API Response
https://github.com/eclipse-tractusx/portal-frontend/issues/454

fix(usermanagement): fix page load issue

---

CHANGELOG.md
src/assets/locales/de/idp.json
src/assets/locales/en/idp.json
src/components/overlays/AddusersIDP/index.tsx

Fix upload of user list results in empty preview and when confirming the upload an empty file is sent to the backend.
Feature broken fix
https://github.com/eclipse-tractusx/portal-frontend/issues/440

fix(idp config): fix user csv file upload results

---

CHANGELOG.md
src/components/shared/basic/ReleaseProcess/OfferContractAndConsent/index.tsx
src/components/shared/basic/ReleaseProcess/components/CommonContractAndConsent.tsx

fixed conformity document deletion issue after uploading document
Uploaded document should get deleted on click of delete icon
Ref: CPLP-3579

fix(service release process): conformity document delete fix

---

CHANGELOG.md
src/components/pages/InviteBusinessPartner/components/InviteList/index.tsx
src/components/shared/basic/ReleaseProcess/AppMarketCard/index.tsx

update pattern in invite business partner section and app release process
sync with back end implementation
NA

fix(company name): pattern update

---

CHANGELOG.md
package.json

ChangeLog creation for portal FE rc-4 of 1.8.0
ChangeLog creation for portal FE rc-4 of 1.8.0
#166

build: changeLog 1.8.0 RC4

---

CHANGELOG.md

Removed duplicate change log
To remove duplicate log.
NA

fix(changelog): remove duplicate log

---

CHANGELOG.md
src/components/overlays/AddusersIDP/index.tsx

Fix blank page issue while uploading JSON File
JSON functionality was not working due to csv file changes
https://github.com/eclipse-tractusx/portal-frontend/issues/441

fix(idp csv upload): fix json file blank page issue

---

CHANGELOG.md
src/assets/locales/de/main.json
src/assets/locales/en/main.json
src/components/overlays/CompanyCertificateDetails/DeleteCompanyCertificateConfirmationOverlay.tsx
src/components/overlays/CompanyCertificateDetails/index.tsx
src/components/pages/CompanyCertificates/CompanyCertificateCard.tsx
src/components/pages/CompanyCertificates/CompanyCertificateElements.tsx
src/components/pages/CompanyCertificates/UploadCompanyCerificate.tsx
src/components/pages/CompanyCertificates/index.tsx
src/features/companyCertification/companyCertificateApiSlice.tsx
src/services/AccessService.tsx

connect listing page, upload certificate and details page to back end api
connect static content with apis
#460 #461 #462 

feat(company certificate): api integration

---

src/assets/locales/en/idp.json

Update description of the register partner overlay
Update the description of the register partner overlay.
Remove the placeholder and give some more explanation.
[Link to Github issue.](https://github.com/eclipse-tractusx/portal-frontend/issues/521)

docs(idp): update register partner overlay description

---

CHANGELOG.md
DEPENDENCIES
package.json
public/index.html
src/components/pages/Admin/components/RegistrationRequests/components/RequestList/index.tsx
src/components/pages/PartnerNetwork/index.tsx
yarn.lock

fixed auto focus issue which was resulted in unhelpful scroll in Partner Network and Application Request page
click action is resulting in auto scroll
#431

fix(scroll): solve unhelpful scroll

---

.github/workflows/build.yml
.github/workflows/release-release_candidate.yml
.github/workflows/release.yml
.github/workflows/release_candidate.yml
.tractusx
NOTICE.md
README.md

change portal-cd references to portal
TRG-2.04 compliance
https://github.com/eclipse-tractusx/portal-cd/issues/131

chore(trg-2.04): change portal-cd references to portal

---

CHANGELOG.md
src/components/pages/AdminBoardDetail/BoardContentDetails.tsx
src/components/pages/AdminBoardDetail/index.tsx
src/components/pages/AppDetail/AppDetailContentDetails.tsx
src/components/pages/AppDetail/components/AppDetailHeader/AppDetailHeader.scss
src/components/pages/CompanySubscriptions/CompanySubscriptionDetail.tsx
src/components/pages/ServiceMarketplaceDetail/index.tsx
src/components/shared/basic/ReleaseProcess/components/RetryOverlay.tsx
src/components/styles/main.scss

Implement Back button instead of simple button
UI Improvements
n/a

feat(app detail): ui update of back button

---

CHANGELOG.md
src/assets/locales/de/main.json
src/assets/locales/en/main.json
src/components/overlays/CompanyCertificateDetails/DeleteCompanyCertificateConfirmationOverlay.tsx
src/components/overlays/CompanyCertificateDetails/index.tsx
src/components/pages/CompanyCertificates/CompanyCertificateCard.tsx
src/types/Constants.ts

connect delete certificate to back end api
new feature
#459 

feat(company certificates): delete api integration

---

.github/workflows/build.yml
.github/workflows/release-release_candidate.yml
.github/workflows/release.yml
.github/workflows/release_candidate.yml
.tractusx
CHANGELOG.md
FILEHEADER.md
NOTICE.md
README.md
package.json
scripts/check-dependencies.md
src/components/pages/RoleDetails/index.tsx

https://github.com/eclipse-tractusx/portal-cd/issues/188

build(1.8.0): merge release into main

---

CHANGELOG.md
FILEHEADER.md
README.md
package.json
scripts/check-dependencies.md
src/components/pages/RoleDetails/index.tsx

Merge the latest changes to the dev branch
To have the latest changes available in the dev branch
[188 ](https://github.com/eclipse-tractusx/portal-cd/issues/188)

build(1.8.0): merge main into dev

---

src/components/pages/SemanticHub/DownloadLink.tsx
src/components/pages/SemanticHub/ModelDetailDialog.tsx

This will fix the described error in #446.
Diagrams were not displayed properly and file download weren't handled correctly. 
#446

fix(aspect models): Fix aspect model diagram display and aspect model file download

---

CHANGELOG.md
DEPENDENCIES
package.json
src/components/pages/AppOverview/ChangeDescription.tsx
yarn.lock

fixed display of the description correctly
When changing an app description, the german and english fields are replaced and fields should save correctly
https://github.com/eclipse-tractusx/portal-frontend/issues/551

fix(change app description): fix description display

---

CHANGELOG.md
src/assets/locales/de/main.json
src/assets/locales/en/main.json
src/components/pages/TechnicalUserManagement/TechnicalUserTable.tsx
src/features/admin/serviceApiSlice.ts

Add Inactive users filter and add api endpoint to filter the data
To allow user can see his inactive users list
https://github.com/eclipse-tractusx/portal-frontend/issues/585

feat(technical user): add inactive users filter

---

CHANGELOG.md
src/components/pages/AppMarketplace/components/AppListSection/index.tsx

Reverts eclipse-tractusx/portal-frontend#605
Product owner doesn't like the implemented solution.

fix(app marketplace): revert change fav icon add/remove

---

CHANGELOG.md
src/components/shared/basic/ReleaseProcess/AppMarketCard/index.tsx
src/components/shared/basic/ReleaseProcess/AppPage/index.tsx
src/components/shared/basic/ReleaseProcess/ContractAndConsent/index.tsx
src/components/shared/basic/ReleaseProcess/OfferCard/index.tsx
src/components/shared/basic/ReleaseProcess/OfferContractAndConsent/index.tsx
src/components/shared/basic/ReleaseProcess/OfferPage/index.tsx
src/components/shared/basic/ReleaseProcess/OfferTechnicalIntegration/index.tsx
src/components/shared/basic/ReleaseProcess/OfferValidateAndPublish/index.tsx
src/components/shared/basic/ReleaseProcess/TechnicalIntegration/index.tsx
src/components/shared/basic/ReleaseProcess/ValidateAndPublish/index.tsx

fixed help links in app release process and service release process
Help links should point to correct documentation
https://github.com/eclipse-tractusx/portal-frontend/issues/493

fix(release process): fix help links

---

DEPENDENCIES
package.json
yarn.lock

Upgrade Shared Components to latest for image loading improvements
The image loading logic has changed in the shared component. We upgrade to use the latest version.
ref Jira: CPLP-3243, -3244, -3273

fix(images): upgrade library to latest with updated image component

---

.github/dependabot.yml

restrict to patch updates (due to the big amount of dependencies)
https://github.com/eclipse-tractusx/portal/issues/219

chore: improve dependabot.yml

---

.github/workflows/build.yml
.github/workflows/checks.yml
.github/workflows/dependencies.yaml
.github/workflows/kics.yml
.github/workflows/pullRequest-lint.yaml
.github/workflows/release-release_candidate.yml
.github/workflows/release.yml
.github/workflows/release_candidate.yml
.github/workflows/trivy-dev.yml
.github/workflows/trivy.yml

upgrade gh actions and change to pinned actions full length commit sha
https://github.com/eclipse-tractusx/portal/issues/225

chore(gh-actions): upgrade and change to pinned commit sha

---

DEPENDENCIES

chore: update dependencies file
IP issues from https://github.com/eclipse-tractusx/portal-frontend/pull/627#issuecomment-2019853895 are now approved

chore: update dependencies file

---

.eslintrc.json
CHANGELOG.md
src/assets/locales/de/main.json
src/assets/locales/en/main.json
src/components/overlays/CompanyCertificateDetails/index.tsx
src/components/pages/CompanyCertificates/CompanyCertificate.scss
src/components/pages/CompanyCertificates/CompanyCertificateCard.tsx
src/components/pages/CompanyCertificates/UploadCompanyCerificate.tsx
src/components/pages/CompanyCertificates/index.tsx
src/features/companyCertification/companyCertificateApiSlice.tsx

- Implementation of New UI Design for Company Certificates
- Show error icon on certificate deletion error scenario
- Update API Endpoint for Fetching Certificate Document
- Use listing page api to fetch certificates in details page
new change request and bug fix
#622 #659 #660 #463 

fix(company certificate): new card ui

---

.github/dependabot.yml

chore(dependabot): fix docker directory
https://github.com/eclipse-tractusx/portal/issues/219

chore(dependabot): fix docker directory

---

.github/workflows/build.yml
.github/workflows/release-release_candidate.yml
.github/workflows/release.yml
.github/workflows/release_candidate.yml

chore: fix node setup step
Introduced due to https://github.com/eclipse-tractusx/portal/issues/225
https://github.com/eclipse-tractusx/portal-shared-components/issues/132

chore: fix node setup step

---

CHANGELOG.md
DEPENDENCIES
src/assets/locales/de/main.json
src/assets/locales/en/main.json

Added missing translations in main.json files
Translations were missing from main.json files
https://github.com/eclipse-tractusx/portal-frontend/issues/714

fix(company subscriptions): updated missing text 

---

CHANGELOG.md
src/assets/locales/de/main.json
src/assets/locales/en/main.json
src/components/pages/EdcConnector/ConfigurationDetailsOverlay.tsx
src/features/connector/connectorApiSlice.ts

update connector details overlay content with dynamic data
convert static to dynamic
#718 

fix(connector): update connector details overlay content

---

CHANGELOG.md
package.json
src/components/pages/EdcConnector/AddConnectorOverlay/components/ConnectorInsertForm.tsx
src/features/admin/serviceApiSlice.ts

https://github.com/eclipse-tractusx/portal/issues/276

build(2.0.0-rc3): merge release into main

---

CHANGELOG.md
index.html
scripts/inject-dynamic-env.sh
src/assets/locales/de/main.json
src/assets/locales/en/main.json
src/features/certification/certificationApiSlice.tsx
src/features/usecase/usecaseApiSlice.ts
src/services/EnvironmentService.ts
src/utils/rtkUtil.ts

Connected Credential Management UI with new Issuer Component
The current existing implementation has a breaking change, the portal endpoints and backend logic have been moved into a new component. Due to this change, the frontend integration needs to get updated.
https://github.com/eclipse-tractusx/portal-frontend/issues/620
Link to pull request in helm chart / portal repository: https://github.com/eclipse-tractusx/portal/pull/279

feat(issuer component): connect with new Issuer Component

---

CHANGELOG.md
src/components/pages/AppOverview/AppOverViewDetails.tsx
src/components/shared/basic/ReleaseProcess/TechnicalIntegration/index.tsx
src/components/shared/basic/ReleaseProcess/ValidateAndPublish/index.tsx
src/components/shared/basic/ReleaseProcess/components/CommonValidateAndPublish.tsx
src/features/appManagement/apiSlice.ts

App Release process fetch app roles endpoint is switched in BE, FE api switch is needed to align with the same 
since BE api is changed
https://github.com/eclipse-tractusx/portal-frontend/issues/704

fix(app release process): update roles endpoint

---

src/assets/locales/de/main.json
src/assets/locales/en/main.json
src/components/overlays/AppMarketplaceRequest/index.tsx
src/components/overlays/ServiceRequest/index.tsx
src/components/pages/CompanySubscriptions/CompanySubscriptions.scss
src/components/pages/EdcConnector/AddConnectorOverlay/components/ConnectorInsertForm.tsx
src/components/pages/EdcConnector/AddConnectorOverlay/index.tsx
src/types/Patterns.ts

Addressed feedback for PR https://github.com/eclipse-tractusx/portal-frontend/pull/717
NA
https://github.com/eclipse-tractusx/portal-frontend/issues/694

feat(technical setup): connector registration overlay

---

CHANGELOG.md
src/components/pages/PartnerNetwork/partnerNetworkTableColumns.tsx

Fix blank page issue
Image was not working from assets folder so replace image from public folder
N/A

fix(partner network): fix blank page issue

---

CHANGELOG.md
package.json
src/assets/locales/de/main.json
src/assets/locales/en/main.json
src/components/Main.tsx
src/components/pages/PartnerNetwork/partnerNetworkTableColumns.tsx
src/components/pages/UsecaseParticipation/UsecaseParticipation.scss
src/components/pages/UsecaseParticipation/index.tsx
src/features/certification/certificationApiSlice.tsx

https://github.com/eclipse-tractusx/portal/issues/308

build(2.0.0-rc6): merge release into main

---

.github/dependabot.yml

add groups for version updates
https://github.com/eclipse-tractusx/portal/issues/300

chore(dependabot): add groups for version updates

---

src/components/overlays/InviteForm/index.tsx

Removed sonar findings
We fix medium sonar findings to improve the overall code quality.
#749

fix(sonar): improve code quality

---

DEPENDENCIES
public/index.html
scripts/inject-dynamic-env.sh
src/services/EnvironmentService.ts
src/types/Patterns.ts

make https in url patterns configurable
enable local sandbox, playground where tls connections might not be feasible

chore: make https configurable in url patterns

---

CHANGELOG.md
src/components/pages/AppSubscription/ActivateSubscriptionOverlay/index.tsx
src/features/appSubscription/appSubscriptionApiSlice.ts

Fix blank page issue on autosetup call
White page error, API response can not get managed
https://github.com/eclipse-tractusx/portal-frontend/issues/818

fix(app subscription): fix blank page on autosetup call

---

CHANGELOG.md
src/assets/locales/de/main.json
src/assets/locales/en/main.json
src/components/pages/CompanyWallet/CompanyWallet.scss
src/components/pages/CompanyWallet/Overlay.tsx
src/components/pages/CompanyWallet/RuleCard.tsx
src/components/pages/CompanyWallet/index.tsx
src/features/compayWallet/companyWalletApiSlice.ts

add revoke credential feature
>  Revoke Icon Addition
> Tooltip on Hover
> Confirmation Overlay
> Success/Error Handling
new feature
#767 

feat(company wallet): add revoke credential

---

CHANGELOG.md
src/features/deleteCompany/deleteCompanyApiSlice.ts

update decline company api info
typo error
#830 

fix(decline): fix typo

---

CHANGELOG.md
src/components/pages/UserManagement/AppArea/index.tsx

App Access Management UI Bug with carousel element
UI broken. Instead of displaying the cards in a row they are displayed vertical.
https://github.com/eclipse-tractusx/portal-frontend/issues/814

fix(app access management): fix carousel element issue

---

CHANGELOG.md
DEPENDENCIES
package.json
src/assets/locales/de/main.json
src/assets/locales/en/main.json
src/components/overlays/OSPRegister/OSPRegisterContent.tsx
src/components/pages/Admin/components/RegistrationRequests/registrationTableColumns.tsx
src/components/pages/AppSubscription/ActivateSubscriptionOverlay/index.tsx
src/components/pages/AppSubscription/AppSubscriptionDetailOverlay/index.tsx
src/components/pages/AppUserManagement/components/AppUserDetailsTable/index.tsx
src/components/pages/CompanyWallet/CompanyWallet.scss
src/components/pages/CompanyWallet/Overlay.tsx
src/components/pages/CompanyWallet/RuleCard.tsx
src/components/pages/CompanyWallet/index.tsx
src/components/pages/EdcConnector/AddConnectorOverlay/components/ConnectorInsertForm.tsx
src/components/pages/EdcConnector/AddConnectorOverlay/index.tsx
src/components/pages/UserManagement/AppArea/index.tsx
src/components/shared/basic/Input/BasicInput.tsx
src/components/shared/basic/Input/ValidatingInput.tsx
src/components/shared/frame/UserList/index.tsx
src/features/admin/networkApiSlice.ts
src/features/admin/serviceApiSlice.ts
src/features/appManagement/apiSlice.ts
src/features/appSubscription/appSubscriptionApiSlice.ts
src/features/compayWallet/companyWalletApiSlice.ts
src/features/deleteCompany/deleteCompanyApiSlice.ts
src/types/Config.tsx
src/types/Patterns.ts
yarn.lock

build(2.0.0-rc9): merge release into main

---

CHANGELOG.md
src/assets/locales/de/main.json
src/assets/locales/en/main.json
src/components/pages/AdminCredential/AdminCredential.scss
src/components/pages/AdminCredential/AdminCredentialElements.tsx

Credential Request Management Board Improvements
UI Improvements
https://github.com/eclipse-tractusx/portal-frontend/issues/619

feat(admin credential): board improvements

---

CHANGELOG.md
README.md
package.json

finalize version 2.0.0
https://github.com/eclipse-tractusx/sig-release/issues/671

build(2.0.0): bump version and update docs

---

CHANGELOG.md
src/assets/locales/de/main.json
src/assets/locales/en/main.json
src/components/pages/AdminCredential/AdminCredential.scss
src/components/pages/AdminCredential/AdminCredentialElements.tsx

Improvements on the Management Board
UI Enhancements for more user friendly
https://github.com/eclipse-tractusx/portal-frontend/issues/851

fix(credential request): ui improvements

---

CHANGELOG.md
src/assets/locales/de/main.json

validate and update translations
german files are having english texts
#892 

fix(locale): update translations

---

CHANGELOG.md
package.json

https://github.com/eclipse-tractusx/portal/issues/398

build(2.2.0-rc1): merge release into main

---

CHANGELOG.md
src/components/pages/Admin/components/RegistrationRequests/CompanyDetailOverlay/CompanyDetailsHelper.tsx
src/components/pages/Admin/components/RegistrationRequests/CompanyDetailOverlay/index.tsx
src/components/pages/Admin/components/RegistrationRequests/RegistrationRequests.scss
src/components/pages/Admin/components/RegistrationRequests/registrationTableColumns.tsx
src/components/pages/AppSubscription/AppSubscriptionDetailOverlay/style.scss
src/features/admin/applicationRequestApiSlice.ts

Implement New UI Design for Customer Detail Data Overlay
The customer detail data overlay that appears after clicking the detail button (arrow button) on the applicationRequests page needs to be updated to match the new UI design provided in the Figma.
https://github.com/eclipse-tractusx/portal-frontend/issues/921

feat(customer details): implement new UI design for customer detail

---

src/types/Patterns.test.ts
src/types/Patterns.ts

Fix the name pattern for persons
Some valid names were not accepted. Extended the list of names in the unit tests and adjusted pattern.
n/a

fix: person name pattern

---

CHANGELOG.md
src/components/pages/Admin/components/RegistrationRequests/CompanyDetailOverlay/index.tsx
src/components/pages/Admin/components/RegistrationRequests/index.tsx

Fixed 'activeTab' conditions to load data for Tab-2(Registration Process)
The condition was missed for activeTab in https://github.com/eclipse-tractusx/portal-frontend/issues/921
https://github.com/eclipse-tractusx/portal-frontend/issues/921

fix(application-requests): fix data load

---

CHANGELOG.md
DEPENDENCIES
package.json
src/components/pages/PartnerNetwork/components/BusinessPartnerDetailOverlay/BusinessPartnerDetail.tsx
src/components/pages/PartnerNetwork/index.tsx
src/features/newPartnerNetwork/partnerNetworkApiSlice.ts
yarn.lock

search url updated with /members.
change GET to POST request and update the FE logic accordingly
wrong search url being used
#980 

fix(partner network): interface change

---

src/assets/locales/de/main.json
src/assets/locales/en/main.json
src/components/overlays/CSVUploadOverlay/index.tsx
src/components/pages/CompanyData/components/CompanyAddressList.tsx
src/components/pages/CompanyData/index.tsx
src/features/companyData/companyDataApiSlice.tsx
src/features/companyData/slice.ts
src/services/AccessService.tsx
src/types/Config.tsx
src/types/Constants.ts

* support pagination in company data listing page
* add column header to status and details section
* enhance disable confirm button logic to support regEx also
* upload csv to create address and site
* create an overlay to accept the csv
* success modal with appropriate message
* error modal to show server response along with copy to clip board option
new request
#1026 #1027 

feat(company data): upload csv

---

CHANGELOG.md
package.json

* update the changelog
* bump version for v2.2.0-RC2
To publish a new version for the frontend
N/A

build(release): bump version for v2.2.0-RC2

---

CHANGELOG.md
DEPENDENCIES
package.json
src/assets/locales/de/main.json
src/assets/locales/en/main.json
src/components/overlays/CSVUploadOverlay/index.tsx
src/components/pages/CompanyData/components/CompanyAddressList.tsx
src/components/pages/CompanyData/components/EditForm.tsx
src/components/pages/CompanyData/components/FormFields.tsx
src/components/pages/CompanyData/components/SelectList.tsx
src/components/pages/CompanyData/index.tsx
src/components/pages/IDPManagement/IDPList.tsx
src/components/pages/OnboardingServiceProvider/OnboardingServiceProvider.scss
src/components/pages/OnboardingServiceProvider/OnboardingServiceProvider.tsx
src/components/pages/PartnerNetwork/components/BusinessPartnerDetailOverlay/BusinessPartnerDetail.tsx
src/components/pages/PartnerNetwork/index.tsx
src/features/admin/idpApiSlice.ts
src/features/companyData/companyDataApiSlice.tsx
src/features/companyData/slice.ts
src/features/newPartnerNetwork/partnerNetworkApiSlice.ts
src/services/AccessService.tsx
src/types/Config.tsx
src/types/Constants.ts
src/types/Patterns.test.ts
src/types/Patterns.ts
yarn.lock

Merge the latest release into the main branch
N/A

build: merge release into main

---

CHANGELOG.md
DEPENDENCIES
src/assets/locales/de/main.json
src/assets/locales/en/main.json
src/components/pages/Admin/components/RegistrationRequests/CompanyDetailOverlay/CompanyDetailsHelper.tsx
src/components/pages/Admin/components/RegistrationRequests/RegistrationRequests.scss
src/components/pages/Admin/components/RegistrationRequests/components/CheckList/CheckListFullButtons.tsx
src/components/pages/Admin/components/RegistrationRequests/registrationTableColumns.tsx
src/components/pages/EdcConnector/edcConnectorTableColumns.tsx
src/components/shared/basic/Progress/index.tsx
src/features/admin/applicationRequestApiSlice.ts

Update the status(skipped) in application requests and necessary changes with checkbox in connector management
Due to the implementation of a new status for the self description step we need to be able to show the status skipped in application requests and Connector SD Checkbox should be empty if connector status is skipped
https://github.com/eclipse-tractusx/portal-frontend/issues/948

feat(application requests and connector management): update skipped status

---

CHANGELOG.md
DEPENDENCIES
src/components/pages/CompanyData/components/AddressDetails.tsx
src/components/shared/basic/DeleteObjectContent/style.scss

Fix broken title and description in Modal
Fix translation error
Modal UI is broken
translation key,value is missing
NA

fix(company data): fix broken modal and translation error

---

CHANGELOG.md
DEPENDENCIES
package.json
src/components/overlays/CSVUploadOverlay/index.tsx
src/components/pages/CompanyData/components/CompanyAddressList.tsx
src/components/pages/CompanyData/index.tsx
yarn.lock

remove page notification on download csv template
behaviour is not consistent across the app
#1026 

fix(company data): remove page notification

---

CHANGELOG.md
DEPENDENCIES
package.json
src/components/pages/EdcConnector/AddConnectorOverlay/components/ConnectorInsertForm.tsx
src/components/pages/EdcConnector/AddConnectorOverlay/index.tsx

fixed technical user selection in connector management
Technical user selection is getting reset after input fields are updated 
https://github.com/eclipse-tractusx/portal-frontend/issues/1064

fix(connector management): fix technical user selection

---

CHANGELOG.md
src/assets/locales/de/main.json
src/assets/locales/en/main.json
src/components/pages/CompanySubscriptions/index.tsx
src/features/apps/apiSlice.ts
src/features/apps/types.ts

Update and bind API with filter options
To update API endpoint (GET:/api/apps/subscribed/subscription-status) with BE changes
https://github.com/eclipse-tractusx/portal-frontend/issues/669

feat(company subscriptions): update API with filter options

---

CHANGELOG.md
src/assets/locales/de/main.json
src/assets/locales/en/main.json
src/components/pages/TechnicalUserManagement/TechnicalUserTable.tsx
src/features/admin/serviceApiSlice.ts

Update filters view and logic
As backend logic is restructured,  FE also to be updated
https://github.com/eclipse-tractusx/portal-frontend/issues/1068

feat(technical user management): update filters

---

CHANGELOG.md
package.json

* bump version for v2.2.0
* consolidated changelog for v2.2.0
prepare release
https://github.com/eclipse-tractusx/portal/issues/423

build(2.2.0): bump version and update docs

---

CHANGELOG.md
package.json

https://github.com/eclipse-tractusx/portal/issues/433

build(2.3.0-alpha.1): merge release into main

---

CHANGELOG.md
DEPENDENCIES
src/components/pages/CompanySubscriptions/index.tsx
src/features/apps/apiSlice.ts
src/features/serviceSubscription/serviceSubscriptionApiSlice.ts

Updated API query parameters and fixed Tab UI scroll
To update API endpoint 
https://github.com/eclipse-tractusx/portal-frontend/issues/669

feat(company subscription): update API and fix tab UI scroll

---

CHANGELOG.md
DEPENDENCIES
src/components/pages/TechnicalUserDetails/TechnicalUserDetailsContent.tsx
src/components/pages/TechnicalUserManagement/TechnicalUserTable.tsx
src/components/shared/basic/KeyValueView/index.tsx
src/features/admin/serviceApiSlice.ts

Updated technical user details with user type and service endpoint fields. Also, updated copy icon color for better view and made copy icon available only when value is available
To align fields with BE changes
Updated copy icon visibility and colors for better user experience
https://github.com/eclipse-tractusx/portal-frontend/issues/1078

feat(technical user details): update technical user details 

---

CHANGELOG.md
DEPENDENCIES
src/components/shared/frame/Header/index.tsx
src/types/Config.tsx
src/types/Constants.ts

enhanced permission validation for Onboarding Service Provider
The Onboarding Service Provider Management Page is intended for Onboarding Service Providers (OSPs) only. Therefore, it is necessary to check permissions.
https://github.com/eclipse-tractusx/portal-frontend/issues/1108

feat(ospm): enhance permission validation 

---

CHANGELOG.md
package.json

https://github.com/eclipse-tractusx/portal/issues/444

build(2.3.0-alpha.2): merge release into main

---

src/components/pages/AppMarketplace/components/AppListGroup/index.tsx

Implements an identical card design across the App Marketplace by adopting the list view style for both the list and category views.
**Reason for Choosing List View Design:** The favorite icon is positioned at the top, enhancing accessibility and clarity for users regarding the "add to favorites" functionality.
This change ensures a consistent user experience by maintaining uniform card designs across different views in the App Marketplace.
#1145

fix: unify card design in marketplace to list view style

---

CHANGELOG.md
src/components/pages/OnboardingServiceProvider/OnboardingServiceProvider.tsx

Fixed blank page issue in customer overview tab in onboarding service provider management page
Should not display blank page.
https://github.com/eclipse-tractusx/portal-frontend/issues/1228

fix(ospm): fix blank page

---

DEPENDENCIES
package.json
yarn.lock

upgrade to keycloak-js version 25
to align with Keycloak server version https://github.com/eclipse-tractusx/portal-iam/pull/213
https://github.com/eclipse-tractusx/portal-iam/issues/85

build: upgrade to keycloak-js version 25

---

CHANGELOG.md
package.json

https://github.com/eclipse-tractusx/portal/issues/463

build(2.3.0-alpha.3): merge release into main

---

CHANGELOG.md
package.json
src/assets/locales/de/main.json
src/assets/locales/de/servicerelease.json
src/assets/locales/en/main.json
src/assets/locales/en/servicerelease.json
src/components/pages/Admin/components/RegistrationRequests/CompanyDetailOverlay/index.tsx
src/components/pages/AppDetail/components/AppDetailDocuments/index.tsx
src/components/pages/AppOverview/index.tsx
src/components/pages/ServiceSubscription/index.tsx
src/components/pages/UsecaseParticipation/UsecaseParticipation.scss
src/components/pages/UsecaseParticipation/index.tsx
src/components/shared/templates/Subscription/SubscriptionElements.tsx
src/components/shared/templates/Subscription/index.tsx
src/features/admin/registration/types.ts
src/features/serviceSubscription/serviceSubscriptionApiSlice.ts
src/types/Patterns.test.ts
src/types/Patterns.ts

finalize version 2.3.0-RC2 by merge into main
https://github.com/eclipse-tractusx/portal/issues/465

build(2.3.0-rc2): bump version and update docs

---

CHANGELOG.md
DEPENDENCIES
src/components/pages/Home/components/AppStoreSection/index.tsx

Fix clicking on apps in Home page URL navigation failed.
Clicking on apps in Home page should be navigate particular app URL.
https://github.com/eclipse-tractusx/portal-frontend/issues/1147

fix(home page): clicking apps in Home page navigation failed

---

src/assets/locales/de/main.json
src/assets/locales/en/main.json

update tooltip message and placeholder text in create connector overlay
updated tooltip and placeholder message in create connector overlay
change request
#1297 

fix(connector): update tooltip and placeholder text

---

DEPENDENCIES
package.json
src/components/pages/ServiceMarketplace/RecommendedServices.tsx
src/components/pages/ServiceMarketplace/ServicesElements.tsx
src/components/pages/ServiceReleaseProcess/components/ServiceDetails.tsx
src/components/shared/basic/ReleaseProcess/AppMarketCard/index.tsx
src/components/shared/basic/ReleaseProcess/components/CommonValidateAndPublish.tsx
yarn.lock

Upgrade to shared components v3.7.3
Shared components have been updated. This PR includes the import of the new version and required fixes.
n/a

fix: upgrade to shared components v3.7.3

---

.github/workflows/dependencies.yaml
DEPENDENCIES

Also trigger dependencies.yaml workflow on changes to dependencies.yaml and DEPENDENCIES file.
Prevent wrong/accidental changes to DEPENDENCIES file. Improvement to changes in eclipse-tractusx/portal-frontend#1310.
Refs: eclipse-tractusx/portal-frontend#1306

ci: modify dependencies check on DEPENDENCIES updates

---

CHANGELOG.md
DEPENDENCIES
package.json
src/assets/locales/de/main.json
src/assets/locales/en/main.json
src/components/overlays/AddTechnicalUser/TechnicalUserAddForm.tsx
src/components/overlays/AddTechnicalUser/index.tsx
src/components/overlays/CSVUploadOverlay/index.tsx
src/components/pages/AdminClearingHouseSD/AdminClearingHouseSD.scss
src/components/pages/AdminClearingHouseSD/AdminClearingHouseSDElements.tsx
src/components/pages/AppOverview/ChangeImage.tsx
src/components/pages/CompanyData/components/CompanyAddressList.tsx
src/components/pages/EdcConnector/ConnectorDetailsOverlay.tsx
src/components/pages/EdcConnector/index.tsx
src/components/pages/Home/components/AppStoreSection/index.tsx
src/components/pages/OnboardingServiceProvider/OnboardingServiceProvider.tsx
src/components/pages/ServiceMarketplace/RecommendedServices.tsx
src/components/pages/ServiceMarketplace/ServicesElements.tsx
src/components/pages/ServiceReleaseProcess/components/ServiceDetails.tsx
src/components/shared/basic/Dropzone/index.tsx
src/components/shared/basic/ReleaseProcess/AppMarketCard/index.tsx
src/components/shared/basic/ReleaseProcess/ContractAndConsent/index.tsx
src/components/shared/basic/ReleaseProcess/OfferContractAndConsent/index.tsx
src/components/shared/basic/ReleaseProcess/components/CommonContractAndConsent.tsx
src/components/shared/basic/ReleaseProcess/components/CommonValidateAndPublish.tsx
src/components/shared/frame/UserList/index.tsx
src/features/admin/serviceApiSlice.ts
src/types/Constants.ts
yarn.lock

finalize version 2.3.0-RC3 by merge into main
https://github.com/eclipse-tractusx/portal/issues/465

build(2.3.0-rc3): bump version and update docs

---

.github/workflows/trivy-main.yml
.github/workflows/trivy.yml
CHANGELOG.md
package.json
src/assets/locales/de/main.json
src/assets/locales/en/main.json
src/components/overlays/AddTechnicalUser/TechnicalUserAddForm.scss
src/components/overlays/AddTechnicalUser/TechnicalUserAddForm.tsx

finalize version 2.3.0-RC4 by merge into main
https://github.com/eclipse-tractusx/portal/issues/465

build(2.3.0-rc4): bump version and update docs

---

index.html

Revert overwritten example values index file
Need to update index file example values.

fix: revert overwritten example values

---

DEPENDENCIES
package.json
yarn.lock

Upgrade to latest Shared Components 3.7.5
To have latest library improvements and bug fixes in the frontend.
n/a

chore: upgrade to shared components 3.7.5

---

src/components/pages/AppSubscription/ActivateSubscriptionOverlay/style.scss
src/components/pages/CompanyWallet/style.scss
src/components/pages/TechnicalUserManagement/TechnicalUserTable.tsx
src/components/shared/basic/ReleaseProcess/ReleaseProcessSteps.scss
src/components/shared/templates/StaticTemplateResponsive/Cards/TextImageSideBySideWithSections.tsx
src/components/shared/templates/StaticTemplateResponsive/index.tsx

Fixes removing react warnings
Implementation flaws caused warnings in dev mode
#1269

fix(react): remove react warnings

---

package.json

finalize version 2.4.0-RC1 by merge into main
Refs: eclipse-tractusx/portal#502

build(2.4.0-rc1): bump version

---

src/components/shared/basic/ReleaseProcess/TechnicalIntegration/AddTechUserForm.tsx

align text and icon vertically and horizontally to the centre
eye icon is not aligned
NA

fix: eye icon alignment issue

---

DEPENDENCIES
package.json
yarn.lock

Upgrade to latest Shared Components 3.7.6
To have latest library improvements and bug fixes in the frontend.
https://github.com/eclipse-tractusx/portal-shared-components/issues/425

chore: upgrade components to 3.7.6

---

src/assets/locales/de/main.json
src/assets/locales/en/main.json

Fixed translations for App Overview "Behavior Twin" Category view
- **App Marketplace**:
- Fixed translations for App Overview "Behavior Twin" Category view. [#1527](https://github.com/eclipse-tractusx/portal-frontend/pull/1527)
Translation is missing for App Overview "Behavior Twin" Category view
https://github.com/eclipse-tractusx/portal-frontend/issues/1517

fix(app marketplace): fix translations

---

DEPENDENCIES
package.json
yarn.lock

upgrade axios dependency
dependabot
https://github.com/eclipse-tractusx/portal/issues/524

build: update axios dependency

---

CHANGELOG.md
package.json

finalize version 2.4.0-RC2 by merge into main
https://github.com/eclipse-tractusx/portal/issues/524

build(2.4.0-RC2): bump version and update docs

---

CHANGELOG.md
package.json

* bumped version for v2.4.0
* consolidated changelog for v2.4.0
* added known knowns
prepare release
https://github.com/eclipse-tractusx/portal/issues/524

build(2.4.0): bump version and update docs

---

CHANGELOG.md

Update changelog for 2.5.0-RC1 release
Add changelog for 2.5.0-RC1.
https://github.com/eclipse-tractusx/portal/issues/541

docs: update changelog for 2.5.0-RC1 release

---

public/template_app_role_upload.csv
src/components/pages/AppOverview/AddRolesOverlay.tsx

- Fix typos in add additional roles CSV file
- Adjust CSV upload logic to match added description_en & description_de columns
**Changelog entry**
```
App release process
- Fix user roles CSV template and read logic [#1584](https://github.com/eclipse-tractusx/portal-frontend/pull/1584
```
Uploading a CSV based on the template provided on the app add additional roles overlay was returning an error and blocking a successful file upload. 
#1583

fix: adjust CSV upload logic to match template structure

---

CHANGELOG.md
package.json

* bump version
* update docs (and add known knowns)
To prepare the branch for the release v2.5.0
[#548](https://github.com/eclipse-tractusx/portal/issues/548)

build(2.5.0): bump version and update docs

---

CHANGELOG.md
package.json

Update to version v2.6.0-RC1
https://github.com/eclipse-tractusx/portal/issues/557

build(v2.6.0-RC1): bump version and update docs

---

src/components/overlays/AddServiceProvider/index.tsx
src/components/pages/OnboardingServiceProvider/OnboardingServiceProvider.tsx
src/features/store.ts

skip immediate validate logic in idp form.
remove duplicate entry from redux store
- **IDP form**
- removed input validation on overlay open [#1627](https://github.com/eclipse-tractusx/portal-frontend/pull/1627)
on opening overlay, fields are validated and error messages are shown
#1589 

fix: skip immediate validation from idp form

---

CHANGELOG.md
package.json
src/components/overlays/AddServiceProvider/index.tsx
src/components/pages/OnboardingServiceProvider/OnboardingServiceProvider.tsx
src/features/serviceManagement/apiSlice.ts
src/features/store.ts

Merge v2.6.0 into main
**Do not squash**
Update main branch with latest changes
Refs: eclipse-tractusx/portal#557

chore(v2.6.0): merge release into main
