eclipse-tractusx/portal-frontend

.conf/Dockerfile.full
.conf/Dockerfile.prebuilt
.conf/notice-portal.md
.github/workflows/build.yml
.github/workflows/release-release_candidate.yml
.github/workflows/release.yml
.github/workflows/release_candidate.yml
.github/workflows/trivy-dev.yml
.github/workflows/trivy.yml
README.md

- enable workflows for push to dockerhub
- change to tags from docker metadata action
- add notice for docker images and license in readme https://github.com/eclipse-tractusx/portal-frontend/issues/16
- remove references to consortia envs from readme
- remove temporary security fixes
https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-05
https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-06

build: enable push to dockerhub

---

cx-portal/src/components/shared/templates/StaticTemplateResponsive/StaticTemplate.scss

Use strong element with a class identifier to resolve issue in other places.
Strong element used in other places broken because of the common style
Common css on strong element breaking styles in other pages.

bugfix(general) : use strong tag with specific class name

---

cx-portal/src/components/shared/templates/StaticTemplateResponsive/StaticTemplate.scss

Style fix based on multiple identifier rather than just class name
JSON string does not provide class name.
NA

bugfix(static template): text color and position of tooltip issue fix

---

cx-portal/src/components/shared/basic/ReleaseProcess/components/CommonContractAndConsent.tsx
cx-portal/src/components/shared/templates/StaticTemplateResponsive/StaticTemplate.scss

Consent information not saved after coming back from step 4 to step3.
Positioning tooltip to the right instead of bottom.
Saved information not shown properly to the user.
Tooltip component rendered behind another and not visible to the user
NA

bugfix(release process) : step3 check box issue fix. Tooltip position issue fix

---

CHANGELOG.md
cx-portal/src/assets/locales/de/servicerelease.json
cx-portal/src/assets/locales/en/servicerelease.json
cx-portal/src/components/shared/basic/ReleaseProcess/OfferCard/index.tsx
cx-portal/src/components/shared/basic/ReleaseProcess/OfferPage/index.tsx
cx-portal/src/features/apps/apiSlice.ts

1. Support SERVICE_LEADIMAGE in service release process step1.
2. Allow user to delete the uploaded image/doc in both step1 or step2
3. Show notifier on delete action.
Notifier - User has no clue on whether the action is completed or not.
NA

updates(service release process) : support load image in service release flow. show notifier on delete document/image

---

CHANGELOG.md
cx-portal/src/components/pages/EdcConnector/AddConnectorOverlay/index.tsx

On opening overlay in the connector page, clear the data entered previously.
after creating a connector successfully and now reopening the connector registration - previously entered data are still visible.
NA

bugfix(connector) : clear previously added data in the overlay

---

CHANGELOG.md
cx-portal/src/components/pages/Admin/components/RegistrationRequests/index.tsx

Hide load element on opening the bpn overlay
When entering a BPN manually inside the registration approval board, I can't update the BPN of a second registration request without refreshing the page - reason - the add bpn overlay keeps showing a load element.
NA

bugfix(registration process) : bpn overlay keeps showing a load element

---

CHANGELOG.md
cx-portal/src/components/pages/ServiceAdminBoardDetail/index.tsx

Service Admin Board Detail: Page not displayed on service navigation
To avoid displaying empty screen
Ref: CPLP-2796

bugfix(service admin): Page not displayed issue fix

---

CHANGELOG.md
cx-portal/src/components/shared/templates/StaticTemplateResponsive/Cards/TextCenterAlignedBody2.tsx

Use case section is showing empty because some of the contents are not parsed properly from the usecase.json or companyroles.json. To avoid this, use html tags in the components section and use appropriate name in the json
use case section is showing empty
NA

bugfix(usecase) : configure br tag in the components to avoid json parsing error

---

CHANGELOG.md
cx-portal/src/components/pages/Organization/index.tsx
cx-portal/src/components/pages/UserManagement/AppArea/index.tsx
cx-portal/src/features/apps/apiSlice.ts

Show missing subscription info.
Backend api has updated with content and meta attributes in the response but front end app was still looking for array of objects in the response. Now updated the data in the code as well.
Subscription section is empty
NA

bugfix(my organisation) : Show missing subscription info

---

cx-portal/src/components/shared/basic/ReleaseProcess/OfferCard/index.tsx

do refresh on whenever the step is loaded
While coming back from step2, added image in step1 is not appearing
NA

bugfix(service release): do refresh on action back from step2

---

CHANGELOG.md
cx-portal/src/components/shared/basic/ReleaseProcess/components/CommonValidateAndPublish.tsx

show lead service image in validate & publish step. fetch details from server and show the appropriate image
Service lead image is missing in the horizontal card
NA

bugfix(service release process): show lead service image in validate & publish step

---

CHANGELOG.md
cx-portal/src/components/shared/templates/Subscription/SubscriptionElements.tsx
cx-portal/src/features/appSubscription/appSubscriptionApiSlice.ts

Show service or app name on subscription management card
attribute name has been changed in the backend
NA

bugfix(subscription management): show service or app name

---

CHANGELOG.md
cx-portal/src/components/pages/TechnicalUserDetails/TechnicalUserDetailsContent.tsx
cx-portal/src/components/shared/basic/ReleaseProcess/AppMarketCard/index.tsx

app lead image load issue fix
When leadimage is in status "INACTIVE", the image in card is not displayed, but should display document details for document upload
Ref: CPLP-2848

bugfix(app release process): app lead image load issue fix

---

cx-portal-shared-components/README.md

Add a note the shared components are deprecated
The shared components are moving to a new repository location and npm package name. Make sure users are aware of this change and switch to the new version.
n/a

chore(shared-components): add deprecation note

---

CHANGELOG.md
cx-portal/src/components/pages/ServiceMarketplaceDetail/index.tsx

Clear already set success state back to false before navigating to another service
Service Subscription - Subscription Button cross service highlighted
NA

bugfix(service marketplace): clear state on change subscription service

---

CHANGELOG.md
cx-portal/src/assets/locales/de/notification.json
cx-portal/src/assets/locales/en/notification.json
cx-portal/src/components/pages/NotificationCenter/NotificationItem.tsx
cx-portal/src/components/pages/NotificationCenter/Notifications.scss
cx-portal/src/components/pages/NotificationCenter/index.tsx
cx-portal/src/components/pages/TechnicalUserDetails/TechnicalUserDetailsContent.tsx
cx-portal/src/features/notification/apiSlice.ts
cx-portal/src/features/notification/types.ts

Show a tick mark for the notification which are all already addressed or required action taken.
Allow user to mark notification read/unread
Feature
NA

feat(notification): mark notification done and allow to mark read/unread

---

src/components/shared/frame/SlidingMainHeader/SlidingMainHeader.scss

render width based on the browser window size
when switching the portal width screens get rendering issues
NA

bugfix(home carousel): responsive issue fix

---

DEPENDENCIES
package.json
src/components/overlays/AppMarketplaceRequest/index.tsx
src/components/pages/AppDetail/components/AppDetailHeader/index.tsx
yarn.lock

App Details page broken after switch to new shared components.
The Material UI upgrade broke some exports which caused an error on app details page.
JIRA: CPLP-2914

bugfix(apps): app details working with new shared components

---

DEPENDENCIES
src/features/notification/apiSlice.ts

remove onlyDueDate=true query parameter from url for action required option
bugfix
NA

bugfix(notification): remove onlyDueDate=true

---

CHANGELOG.md
src/assets/locales/de/main.json
src/assets/locales/en/main.json
src/components/pages/AppOverview/ChangeDescription.tsx
src/components/pages/AppOverview/index.tsx
src/features/appManagement/apiSlice.ts

Change Description(sub menu) functionality added for active apps 
To enhance.
Ref: CPLP-1558,1559

sub-menu(description): implemented change description

---

src/components/shared/templates/StaticTemplateResponsive/Cards/TitleDescriptionAndSectionlink.tsx

element placed behind the stage navigation header on scroll to top. subtract the offset value with 200 to stop just before the stage header navigation
not able to see the section title
NA

bugfix(static page): fix inline scroll height

---

CHANGELOG.md
src/components/styles/main.scss

add max width to the portal body
contents are getting smaller on zoom out
Positive Example - Microsoft Page
https://github.com/eclipse-tractusx/portal-frontend/issues/127

bugfix(portal): add max width to the portal body

---

CHANGELOG.md
src/components/shared/basic/ReleaseProcess/AppPage/index.tsx
src/components/shared/basic/ReleaseProcess/ContractAndConsent/index.tsx
src/components/shared/basic/ReleaseProcess/components/CommonContractAndConsent.tsx

Fixed issue - upon upload of the conformity certificate, previous selected consents are gone
Previously selected checkbox values are changed on conformity document change
Ref: CPLP-2885

fix(app-release-process): selected values disappears

---

src/assets/locales/de/main.json
src/assets/locales/en/main.json
src/components/pages/EdcConnector/AddConnectorOverlay/components/ConnectorTypeSelection.tsx
src/components/pages/EdcConnector/AddConnectorOverlay/index.tsx
src/features/admin/userApiSlice.ts

fetch ownCompanyDetails in connectors page. disable connector type selection option based on available company roles in the ownCompanyDetails api response
new change request
NA

updates(connector): disable connector type selection

---

src/components/pages/EdcConnector/index.tsx

remove subscriptionId from technicalUserId attribute and pass empty
technicalUserId should not have any value. It stays empty
NA

bugfix(connector): technicalUserId stays empty

---

src/types/Config.tsx

change app management page role. it should be add_apps
app management page has add_service_offering as role.
NA

bugfix(config): change app management page role

---

src/assets/locales/de/main.json
src/assets/locales/en/main.json
src/components/overlays/UpdateCertificate/index.tsx

Dynamic Error as per API response
To make error more understandable
N/A

fix(certificate): error message

---

src/assets/locales/de/notification.json
src/assets/locales/en/notification.json
src/components/pages/NotificationCenter/NotificationItem.tsx
src/features/notification/types.ts

create new json text for CREDENTIAL_APPROVAL, CREDENTIAL_REJECTED and SUBSCRIPTION_URL_UPDATE in notification page.
Show credentailType , appName and newUrl in both title and description
CREDENTIAL_APPROVAL & CREDENTIAL_REJECTED shows raw json
NA

updates(notification): add credential approval, credential reject and subscription url msgs

---

src/components/pages/AppOverview/ChangeDescription.tsx

Fixed page break issue when api response don't have value for each language
To fix page break
Ref: CPLP-1558

fix(sub menu-description): fixed page break

---

src/assets/locales/de/notification.json
src/assets/locales/en/notification.json
src/components/pages/NotificationCenter/NotificationItem.tsx

fix typo -> use usecase instead of usecases
"Nofications" page: link "go to use cases" doesn't work
NA

bugfix(notification): fix go to use case link issue

---

src/assets/locales/de/main.json
src/assets/locales/en/main.json
src/components/pages/EdcConnector/AddConnectorOverlay/components/ConnectorInsertForm.tsx
src/components/pages/EdcConnector/AddConnectorOverlay/index.tsx
src/components/pages/EdcConnector/index.tsx
src/types/Patterns.ts

handle empty customer link section in managed connectors
make sure that the connector registration can not get triggered, if the Customer Link is not selected
NA

bugfix(connectors): do not allow confirm without customer link

---

src/components/pages/AppSubscription/ActivateSubscriptionOverlay/index.tsx

Overlay fix of activation response
Overlay was not appearing after activation
n/a

fix(app activation): overlay fix

---

src/components/shared/basic/ReleaseProcess/OfferCard/index.tsx

do not erase data which are already added to the form on deleting uploaded image
ServiceCard Deletion of Image deletes all Entries
NA

bugfix(service card): do not allow to erase

---

DEPENDENCIES
src/components/shared/basic/ReleaseProcess/components/CommonContractAndConsent.tsx

Fixed save functionality for contract and consent to stay in same page on "Save" click
Service Contract & Consent Save acts as Save & Proceed
Ref: TEST-1235

fix(service release process): fixed save functionality

---

DEPENDENCIES
LICENSES/CC-BY-4.0.txt
package.json
public/cx-logo-gray.svg.license
public/cx-logo-text.svg.license
public/cx-logo.svg.license
public/orange-background-full.svg.license
public/orange-background-head.svg.license
src/assets/icons/perm_identity.svg.license
src/assets/logo/cx-logo-short.svg.license
yarn.lock

- change license notice for images
- add second license
https://github.com/eclipse-tractusx/portal-shared-components/pull/34 should be merged first, so that 2.0.19 of shared-components can be used.
https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-07
n/a

chore(trg-7-07): change license notice for images

---

CHANGELOG.md
DEPENDENCIES
package.json
yarn.lock

- bump version
- update changelog
- update shared-components lib  https://github.com/eclipse-tractusx/portal-shared-components/pull/40
to prepare the release branch for the latest release
N/A

release: finalize v1.6.0-RC8

---

src/assets/locales/de/main.json
src/assets/locales/en/main.json
src/components/pages/AppOverview/AppOverviewList.tsx
src/components/pages/AppOverview/index.tsx
src/components/pages/AppOverviewNew/index.tsx
src/components/shared/templates/AdminBoard/AdminBoardElements.tsx
src/components/shared/templates/AdminBoard/index.tsx
src/components/shared/templates/Subscription/SubscriptionElements.tsx
src/components/shared/templates/Subscription/index.tsx

show error bar component in case of failure in the following pages
1. app overview
2. service overview
3. app subscription
4. service subscription
5. app admin board
6. service admin board
do not show No Items available message even for the api call failure
NA

updates(error bar): use error bar component

---

NOTICE.md
public/cx-logo-gray.svg.license
public/cx-logo-text.svg.license
public/cx-logo.svg.license
public/orange-background-full.svg.license
public/orange-background-head.svg.license
src/assets/logo/cx-logo-short.svg.license

- attribute logos in notice
- change source in some license notice files
[third-party-content](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-07#third-party-content)
n/a

chore: attribute logos in notice

---

CHANGELOG.md
NOTICE.md
package.json
public/cx-logo-gray.svg.license
public/cx-logo-text.svg.license
public/cx-logo.svg.license
public/orange-background-full.svg.license
public/orange-background-head.svg.license
src/assets/logo/cx-logo-short.svg.license

Merge release branch  for v1.6.0 into main
to wrap up release process
N/A

release(1.6.0): merge release into main

---

src/assets/locales/de/main.json
src/assets/locales/en/main.json
src/components/overlays/UpdateCertificate/index.tsx
src/components/pages/CertificateCredentials/index.tsx
src/features/certification/certificationApiSlice.tsx

Add certificate type in certificate upload overlay
To select the certificate type
n/a

feat(certificate): add certificate type

---

src/assets/locales/de/main.json
src/assets/locales/en/main.json
src/components/overlays/EditUsecase/index.tsx
src/components/overlays/UpdateCertificate/index.tsx

Add maxfilesize for usecase and certificate upload
To add this according to backend size
n/a

feat(credential upload): add maxfilesize

---

src/assets/locales/de/notification.json
src/assets/locales/en/notification.json
src/components/pages/NotificationCenter/NotificationItem.tsx
src/features/notification/types.ts

show app name, roles info for app_roles_added notification type
content update
NA

updates(notification): show roles information

---

CHANGELOG.md
src/assets/locales/de/servicerelease.json
src/assets/locales/en/servicerelease.json
src/components/pages/ServiceReleaseProcess/components/ServiceListOverview.tsx

Added Sub menu for active services in service overview
To enhance service overview
Ref: CPLP-3181

feat(service overview): add sub menu

---

CHANGELOG.md
DEPENDENCIES
src/assets/locales/de/main.json
src/assets/locales/en/main.json
src/components/pages/AppOverview/AppOverviewList.tsx
src/components/pages/AppOverview/ChangeDocuments.tsx
src/types/Config.tsx
src/types/Constants.ts

Added sub-menu for change documents for active apps
To enhance active apps
Ref: CPLP-3084

feat(appoverview): add change documents sub menu

---

CHANGELOG.md
DEPENDENCIES
src/components/shared/templates/StaticTemplateResponsive/StaticTemplate.scss

fix last section background color issue
Footer / Page Background color issue
NA

bugfix(dataspace): fix background color

---

CHANGELOG.md
src/components/shared/templates/Templates.scss

sub navigation header label should be aligned to left instead of centre
label is left aligned
NA

bugfix(sub navigation header): align label to the left

---

src/components/overlays/UpdateCertificate/index.tsx
src/components/pages/CertificateCredentials/index.tsx

Add tooltip to bottom end of input with custom css
UI Enhancement
n/a

feat(certificates): tooltip display to bottom end

---

.github/workflows/build.yml
.github/workflows/release-release_candidate.yml
.github/workflows/release.yml
.github/workflows/release_candidate.yml

build images also for arm64, in addition to amd64
enable localdev umbrella chart: arm64 images needed for usage on Mac
[localdev](https://github.com/eclipse-tractusx/portal-cd/pull/90)

build(arch): build images for arm64

---

CHANGELOG.md
DEPENDENCIES
src/components/shared/basic/ReleaseProcess/AppPage/index.tsx

Fixed double loading of images for app page
On upload of second image, previously uploaded image was also uploading
Ref: CPLP-3303

bugfix(app page): double image load fix

---

CHANGELOG.md
src/components/pages/Home/components/BusinessApplicationsSection/index.tsx

Fixed image display for 'my business applications'
Image was not displayed in card
Ref: CPLP-3213

bugfix(home): image fix for business applications

---

src/components/overlays/OSPRegister/OSPRegisterContent.tsx
src/features/admin/networkApiSlice.ts
src/types/Patterns.ts

Fix validations in OSP Partner Registration
BPN and Unique ID values were incorrectly validated
Ref: Jira CPLP-3191

fix(osp): fix osp validation

---

CHANGELOG.md
src/components/pages/TechnicalUserManagement/TechnicalUserTable.tsx
src/features/admin/serviceApiSlice.ts

Fix - After adding / creating new technical users, list view at bottom "randomly" shows duplicates. Applies to all the views (ALL, MANAGED, OWNED)
duplicate entry issue
NA

bugfix(tech user): fix duplicate entry issue

---

src/assets/locales/de/notification.json
src/assets/locales/en/notification.json
src/components/pages/NotificationCenter/NotificationItem.tsx

change navigation from  Company Role Service Provider  to service marketplace
Link should lead to Service Provider Marketplace as described in notification. https://portal.int.demo.catena-x.net/servicemarketplace
NA

bugfix(notification): change navigation link to service marketplace

---

DEPENDENCIES
package.json
yarn.lock

upgrade axios dependency to v1.6.1
due to vulnerability in previous version
https://github.com/eclipse-tractusx/portal-frontend/pull/352 didn't solve the issue

fix(vulnerability): upgrade axios dependency

---

CHANGELOG.md
src/components/pages/InviteBusinessPartner/components/InviteList/index.tsx
src/components/pages/InviteBusinessPartner/index.tsx
src/features/admin/inviteApiSlice.ts

its expected that the new invited company gets right away updated in the table (see below)
when inviting via the invite overlay a new company, the company gets only displayed as new invited company, if the user refreshes the page.
NA

bugfix(invite): add new invited company gets right away in to the table

---

CHANGELOG.md
src/components/shared/basic/ReleaseProcess/components/CommonContractAndConsent.tsx

Fixed consent check removal issue on save in app release process and service release process
Upon save, checked consent should remain unchanged
Ref: TEST-1519

bugfix(contract and consent): consent check fix

---

CHANGELOG.md
src/components/overlays/NotFound/index.tsx
src/components/overlays/TechnicalUserInfo/index.tsx
src/components/overlays/UpdateCertificate/index.tsx

Change Overlay Button from "Cancel" to "Close"
The action button on the overlay bottom is called "Cancel" which needs to get renamed to "Close". "Cancel" should only get used if the user can actually cancel a process; means the transaction to the backend is not yet done.
n/a

feat(overlay): change from cancel to close

---

DEPENDENCIES
src/components/pages/UsecaseParticipation/index.tsx

Document Icon handling
Enhance the element handling, if no document template url is provided by the backend, then link will be disabled
n/a

fix(usecase): document icon link issue

---

src/assets/locales/de/idp.json
src/assets/locales/en/idp.json
src/components/overlays/AddIDP/index.tsx
src/features/admin/idpApiSlice.ts
src/features/admin/index.ts
src/features/store.ts
src/services/NotifyService.ts

Show only two steps in IDP add stepper when provider type MANAGED is selected.
This type only requires two steps, however three were displayed under certain circumstances.
Note: this is a minor UI glitch, therefore no changelog update.
ref. Jira CPLP-3684

fix(idp): show only two steps when managed idp selected

---

DEPENDENCIES
src/components/pages/Test/index.image.tsx
src/services/EnvironmentService.ts

Removed references to dev env in test code URLs
Code should not contain URLs of existing environments.
#453 

fix(test): remove dev env from image urls

---

CHANGELOG.md
src/components/pages/InviteBusinessPartner/index.tsx

Please include a summary of the change.
Not possible to invite multiple companies in succession as loading button still appears
https://github.com/eclipse-tractusx/portal-frontend/issues/428

fix(invite bpn): fix loading btn issue

---

CHANGELOG.md
src/assets/locales/de/main.json
src/assets/locales/en/main.json
src/components/Main.tsx
src/components/shared/frame/Header/RegistrationDeclinedOverlay/index.tsx
src/components/shared/frame/Header/index.tsx
src/features/registration/registrationApiSlice.ts

Handle portal login navigation as per applicationStatus and applicationType
Portal login navigation handling
https://github.com/eclipse-tractusx/portal-frontend/issues/468

feat(portal navigation): handle navigation as per status

---

src/components/Main.tsx
src/types/Config.tsx

Fix registration redirect not working issue
Not able to redirect to registration portal if url has registration
n/a

fix(portal login): registration navigation

---

CHANGELOG.md
src/components/overlays/OSPRegister/OSPRegisterContent.tsx
src/types/Patterns.ts

Allow 6-36 alphanumeric characters for IDP extId
Existing check for UUIDs is too restrictive.
#477 

fix(IDP management): allow extend range for extID field

---

CHANGELOG.md
src/components/pages/NotificationCenter/NotificationItem.tsx
src/features/notification/apiSlice.ts

Handle set read/unread correctly
Notifications were not shown correcty as read or unread and the count of new items was wrong.
n/a

fix(notifications): handle set read correctly

---

src/components/pages/CompanyWallet/ComapnyWalletSubNavigationHeader.tsx
src/components/pages/CompanyWallet/RuleCard.tsx

display unknown if status is not present instead of inactive. update sub navigation link to credential certificate page
wrong text and link configured
NA

fix(company wallet): update status text and sub navigation link

---

CHANGELOG.md
src/components/pages/CompanyRoles/index.tsx
src/components/shared/templates/Templates.scss

Show company role specific standard library info in the table instead of all.
do not show all std library info in the company role page
NA

fix(company role): show company role specific standard library info

---

CHANGELOG.md
src/components/pages/Admin/components/RegistrationRequests/components/RequestList/index.tsx

Fixed filter related issue
UI breaking issue 
Reset the result after clearing input text
filtering not working
#427 #429 #430 

fix(application requests): search and filter related issues

---

CHANGELOG.md
src/components/overlays/AddUser/index.tsx

Blocked user invite if multiple SHARED/OWN identityProviderTypeId
The "add user not possible" should only get displayed if multiple SHARED/OWN "identityProviderTypeId"  and ignore MANAGED idps for the screen navigation
https://github.com/eclipse-tractusx/portal-frontend/issues/507

fix(idp invite): add user filter idps on shared and own type

---

CHANGELOG.md
src/components/shared/basic/KeyValueView/index.tsx

Removed quotation marks from technical user details
As quotation marks are not needed, it should be removed
Ref: [Issues-492](https://github.com/eclipse-tractusx/portal-frontend/issues/492)

fix(user management): remove quotes

---

CHANGELOG.md
src/components/pages/CertificateCredentials/CertificateElements.tsx
src/components/shared/basic/CertificateCard/index.tsx
src/features/certification/certificationApiSlice.tsx

Changed certificate credential response as per backend
UI enhancement as per backend response
https://github.com/eclipse-tractusx/portal-frontend/issues/515

fix(certificate): change certificate response type

---

CHANGELOG.md
DEPENDENCIES
package.json
yarn.lock

upgrade shared-components package due to CVE-2023-42282 in node-ip package (transitive dependency over @storybook/core-server)
https://github.com/eclipse-tractusx/portal-shared-components/pull/97

chore: upgrade shared-components package

---

src/components/shared/MobileMenu/MenuChildren.tsx
src/components/shared/MobileMenu/MenuItem.tsx
src/components/shared/MobileMenu/MyCompanyLink.tsx
src/components/shared/MobileMenu/index.tsx

show selected parent menu's text in sub menu overlay
new requirement
NA

fix(hamburger): show title in sub menu

---

CHANGELOG.md
src/components/overlays/ConfirmUserAction/index.tsx

Fix logout Redirect URL issue
Logout Redirect URL was wrongly configured
https://github.com/eclipse-tractusx/portal-frontend/issues/505

fix(delete user): fix logout redirect uri issue

---

CHANGELOG.md
src/assets/locales/de/main.json
src/assets/locales/en/main.json
src/components/shared/frame/Header/RegistrationDeclinedOverlay/index.tsx
src/components/shared/frame/Header/index.tsx

Add button to logout from decline overlay
There was no other way to logout from declined user
https://github.com/eclipse-tractusx/portal-frontend/issues/514

feat(decline login): add button to logout user

---

CHANGELOG.md
src/components/shared/basic/KeyValueView/index.tsx

Removed quotation marks when technical user details is copied
Quotes are not required
https://github.com/eclipse-tractusx/portal-frontend/issues/492

fix(technical user): remove quotes

---

.github/workflows/build.yml
.github/workflows/checks.yml
.github/workflows/release-release_candidate.yml
.github/workflows/release.yml
.github/workflows/release_candidate.yml

set node version explicitly
https://github.com/eclipse-tractusx/portal-cd/issues/158

chore: set node version explicitly

---

CHANGELOG.md
src/assets/locales/de/servicerelease.json
src/assets/locales/en/servicerelease.json
src/components/overlays/ActivateServiceSubscription/index.tsx

Changed 'Active Service Subscription' overlay section header for 'Technical User Details'
Header name was duplicated
https://github.com/eclipse-tractusx/portal-frontend/issues/494

fix(service subscription): change header name

---

.github/workflows/build.yml
.github/workflows/release-release_candidate.yml
.github/workflows/release.yml
.github/workflows/release_candidate.yml
.tractusx
NOTICE.md
README.md

change portal-cd references to portal in dev branch via cherry-pick from release branch
Auto-Image-Update to portal (ex. portal-cd) not working as the GH API does apparently not support repository renamings
Ref: https://github.com/eclipse-tractusx/portal-cd/issues/131

fix(repo-renaming): merge change of references also into dev branch

---

CHANGELOG.md
src/components/pages/CertificateCredentials/index.tsx

Fixed code smell error
Fix this expression; length of "certificateTypes" is always greater or equal to zero.

fix(certificate elements): fixed code smell error

---

DEPENDENCIES
package.json
src/components/pages/CompanyCertificates/UploadCompanyCerificate.tsx
src/components/pages/Home/components/BusinessApplicationsSection/index.tsx
src/services/UserService.ts
yarn.lock

Disable some console logs and remove home page warning
The console output was showing some keycloak logs not meant for the portal user and one css warning.
n/a

fix(console): remove logging and warning outputs

---

DEPENDENCIES
package.json
yarn.lock

align keycloak version with centralidp keycloak instance
https://github.com/eclipse-tractusx/portal-iam/issues/62

chore: upgrade keycloak-js dependency to v23.0.7

---

CHANGELOG.md
src/components/pages/AppMarketplace/components/AppListSection/index.tsx

When a user clicks on the favorite button, the button icon change instantly to indicate successful favoritization.
Similarly, when un-favoriting an app, the button icon will update immediately.
The old implementation of the favorite button was causing a problem. When a user clicks on the app's favorite button, the button icon does not change immediately. Instead, the change is only visible after reloading the page. The same issue occurs when trying to un-favorite an app
#464 

fix(app marketplace): change fav icon add/remove

---

CHANGELOG.md
src/components/pages/AppOverview/AddRoles.tsx

fixed empty chip display for additional roles in app overview active apps
Empty chip is displayed when api response is empty
https://github.com/eclipse-tractusx/portal-frontend/issues/553

fix(add roles): fix roles display

---

CHANGELOG.md
src/components/overlays/UpdateCompanyRole/index.tsx
src/components/pages/Admin/components/RegistrationRequests/CompanyDetailOverlay/index.tsx
src/components/pages/Admin/components/RegistrationRequests/index.tsx
src/components/pages/AppMarketplace/components/FavoriteSection/FavoriteItem.tsx
src/components/pages/AppOverview/AppOverViewDetails.tsx
src/components/pages/AppOverview/ChangeImage.tsx
src/components/pages/AppSubscription/ActivateSubscriptionOverlay/index.tsx
src/components/shared/basic/ReleaseProcess/AppMarketCard/index.tsx
src/components/shared/basic/ReleaseProcess/OfferContractAndConsent/index.tsx
src/components/shared/basic/ReleaseProcess/ValidateAndPublish/index.tsx
src/features/admin/applicationRequestApiSlice.ts
src/features/admin/registration/actions.ts
src/features/admin/registration/api.ts
src/features/appManagement/apiSlice.ts
src/features/appSubscription/appSubscriptionApiSlice.ts
src/features/companyRoles/companyRoleApiSlice.ts
src/features/serviceManagement/apiSlice.ts
src/features/serviceMarketplace/serviceApiSlice.ts

remove duplicate api endpoints. keep most appropriate method
improve code maintainability and reduce the risk of introducing bugs.
#587 

fix(apis): remove duplicate api end points

---

CHANGELOG.md
src/components/Main.tsx

To handle this add error page if there is api call error
Thousands of requests are sent when backend not available or api call giving error
https://github.com/eclipse-tractusx/portal-frontend/issues/632

feat(error handling): add errorpage in api call error

---

CHANGELOG.md
src/components/overlays/CompanyCertificateDetails/index.tsx
src/components/pages/CompanyCertificates/index.tsx

display inactive certificate information in details overlay with attached document
inactive certificate info not visible
#692 

fix(company certificate): show inactive certificate information

---

CHANGELOG.md
DEPENDENCIES
index.html
package.json
src/components/overlays/AddAppUserRoles/index.tsx
src/components/overlays/AddMultipleUser/index.tsx
src/components/overlays/OSPConsent/OSPConsentContent.tsx
src/components/pages/Admin/components/RegistrationRequests/components/RequestList/index.tsx
src/components/pages/DeleteCompany/index.tsx
src/components/shared/basic/Dropzone/index.tsx
src/components/shared/basic/Input/DebouncedSearchInput.tsx
src/components/shared/frame/SubHeaderTitle/index.tsx
yarn.lock

Upgrade to Shared Components 3.x
The Shared Component Library has also been upgraded to the Vite Framework and we want to use the latest version.
#537

chore(upgrade): use shared components 3.x

---

CHANGELOG.md
src/components/shared/templates/Templates.scss

disable border color change on focus and hover effect
focus effect is confusing with the selected button behaviour
#690 

fix(sticky header): disable focus effect on button

---

CHANGELOG.md
src/components/pages/EdcConnector/AddConnectorOverlay/components/ConnectorInsertForm.tsx
src/features/admin/serviceApiSlice.ts

fixed white page issue on connector registration with "Existing Technical User" selection
ClientId was null in API response
https://github.com/eclipse-tractusx/portal-frontend/issues/730

fix(technical setup): blank page fix

---

CHANGELOG.md
DEPENDENCIES
src/assets/locales/de/main.json
src/assets/locales/en/main.json
src/components/pages/Admin/components/RegistrationRequests/CompanyDetailOverlay/index.tsx

Displaying incorrect company roles when the requester company has the role "Onboarding Service Provider" added.
The company data overlay should display the correct company roles, regardless of whether the requester company has the role "Onboarding Service Provider" added or not.
https://github.com/eclipse-tractusx/portal-frontend/issues/716

fix(application requests): fix wrong role issue

---

src/components/pages/UsecaseParticipation/UsecaseParticipation.scss
src/components/pages/UsecaseParticipation/index.tsx

Add loader element until content is loading
The user needs to get informed that the content is loading
https://github.com/eclipse-tractusx/portal-frontend/issues/620

feat(usecase): add loader till response generate

---

CHANGELOG.md
package.json
src/assets/locales/de/main.json
src/assets/locales/en/main.json
src/components/Main.tsx

Display Error page if backend not available
When backend isn't available, the app continuously sends thousands of requests
https://github.com/eclipse-tractusx/portal-frontend/issues/632

fix(error handling): display error page if backend not available

---

CHANGELOG.md
src/assets/locales/de/main.json
src/assets/locales/en/main.json
src/components/pages/UsecaseParticipation/UsecaseParticipation.scss
src/components/pages/UsecaseParticipation/index.tsx
src/features/usecase/usecaseApiSlice.ts

Framework Agreement Request Page - Status missing
The credential request status should be displayed correctly based on its actual status.
https://github.com/eclipse-tractusx/portal-frontend/issues/777

fix(usecase-participation): agreement status changes

---

CHANGELOG.md
src/components/pages/AppSubscription/ActivateSubscriptionOverlay/index.tsx
src/components/pages/AppSubscription/AppSubscriptionDetailOverlay/index.tsx
src/components/pages/CompanySubscriptions/CompanySubscriptionDetail.tsx
src/components/pages/Organization/UnSubscribeOverlay.tsx
src/features/appSubscription/appSubscriptionApiSlice.ts

Validation of Technical User UIs for multiple tech user support
The frontend needs to be prepared to handle multiple service account responses.
Possible impacted pages: The backend response of the following 4 endpoints might include multiple technical users:
- appsubscription details page
- servicesubscription details page
- company-subscriptions details page
https://github.com/eclipse-tractusx/portal-frontend/issues/789

feat(subscriptions): multiple tech user support

---

CHANGELOG.md
src/assets/locales/de/main.json
src/assets/locales/en/main.json
src/components/pages/AdminCredential/AdminCredential.scss
src/components/pages/AdminCredential/AdminCredentialElements.tsx
src/features/certification/certificationApiSlice.tsx
src/types/Constants.ts

- Implement Credential Revocation Feature for Issuer Admin Board
- Add Credential Status to Credential Admin Board 
Implement a revocation feature that allows issuers with the "revoke_credentials_issuer" permission to revoke credentials marked as "Active."
https://github.com/eclipse-tractusx/portal-frontend/issues/768
https://github.com/eclipse-tractusx/portal-frontend/issues/774

feat(admin credential): add revoke feature

---

src/components/pages/AppUserManagement/components/AppUserDetailsTable/index.tsx
src/components/shared/frame/UserList/index.tsx
src/types/Config.tsx

Change of roles corresponding to add/edit app user role overlays.
This is for consistency with backend endpoint. [owncompany/users/{companyUserId}/apps/{appId}/roles](https://github.com/eclipse-tractusx/portal-backend/blob/a0b4b0d5729252bdf5b012d4cd592789092b68aa/src/administration/Administration.Service/Controllers/UserController.cs#L239)
Refs: #822
Edits by maintainers allowed:

fix: change required role for app user role overlay

---

CHANGELOG.md
index.html
src/features/appManagement/apiSlice.ts

Update document download functionality on the page /admin-credential
Currently, the document download feature on the page /admin-credential is not functioning correctly. This issue is due to the connection with the outdated backend endpoint {portalhostname}/api/administration/documents/{documentID}. We need to switch to the new provided endpoint {issuercomponenthostname}/credentialRequest/documents/{documentId} located inside the issuer component, instead of the portal backend.
https://github.com/eclipse-tractusx/portal-frontend/issues/763

fix(admin credential): update document download endpoint

---

src/components/overlays/OSPRegister/OSPRegisterContent.tsx
src/components/shared/basic/Input/BasicInput.tsx
src/components/shared/basic/Input/ValidatingInput.tsx
src/features/admin/networkApiSlice.ts
src/types/Patterns.ts

Set default for mandatory unique ID field 
The default was empty and so the request data when field unchanged by user. Also removed the debug output below the form.
#826 

fix(osp): preset unique ID type in partner registration form

---

CHANGELOG.md
src/components/pages/EdcConnector/AddConnectorOverlay/components/ConnectorInsertForm.tsx
src/components/pages/EdcConnector/AddConnectorOverlay/index.tsx
src/features/admin/serviceApiSlice.ts

Fetch all the service accounts and then load the auto complete component.
auto complete does not show up all the service accounts
#752 

fix(connector): show service accounts

---

CHANGELOG.md
src/components/shared/basic/ReleaseProcess/TechnicalIntegration/index.tsx
src/features/appManagement/apiSlice.ts

Integrated role deletion with BE api reponse
With BE changes, roleId is available for roles, which should be used to delete particular role.
https://github.com/eclipse-tractusx/portal-frontend/issues/849

fix(app release process): delete role

---

src/types/Config.tsx
src/types/Constants.ts

Added ROLES.MY_ORGANIZATION_VIEW constant and use this to decide access for PAGES.ORGANIZATION
I was unsure about the intention for **unused** ROLES.ORGANIZATION_VIEW @oyo. Alternatively we can use that one instead.
With role to access data for my organization I also want access to FE view. There is a mismatch between [BE endpoint](https://github.com/eclipse-tractusx/portal-backend/blob/73e24a69521f7ef757985328520b54c0c6649c71/src/administration/Administration.Service/Controllers/CompanyDataController.cs#L55-L69) and FE page role requirement.
Refs: [#856](https://github.com/eclipse-tractusx/portal-frontend/issues/856)

feat(my organization view): Change required role for my organization view

---

DEPENDENCIES
package.json
src/components/shared/frame/Footer/index.tsx
yarn.lock

use scroll to top button component from shared components
move scroll to top button to shared components
#675 

feat: use scroll to top component from shared components

---

.github/dependabot.yml
.github/workflows/build.yml
.github/workflows/dependencies.yaml
.github/workflows/kics.yml
.github/workflows/release.yml
.github/workflows/trivy-main.yml

get rid of dev branch: adjust workflows
https://github.com/eclipse-tractusx/portal/issues/243

chore(dev-flow): maintain latest changes in main branch

---

CHANGELOG.md
src/components/pages/EdcConnector/ConnectorDetailsOverlay.tsx
src/features/connector/connectorApiSlice.ts

Fixed blank page issue on clicking on details
As clicking on connector details leads to blank page
https://github.com/eclipse-tractusx/portal-frontend/issues/924

fix(connector-details): fix blank page

---

CHANGELOG.md
src/components/overlays/EditPortalRoles/index.tsx

Users/Admins are able to deselect all roles assigned to them and confirm during role updates.
Users should not be able to confirm the role update after deselecting all roles assigned to them. At least one role should remain selected at all times.
Users should not be able to confirm the role update after deselecting all roles assigned to them. At least one role should remain selected at all times.
Please include an explanation of why this change is necessary as well as relevant motivation and context. List any dependencies that are required for this change.
https://github.com/eclipse-tractusx/portal-frontend/issues/919

fix(user management): fix disable button state when deselect all checkboxes [updated]

---

CHANGELOG.md
src/features/admin/serviceApiSlice.ts

update get endpoint for 'Connect Company Connector' to consider technical user status
The API call currently lists all technical users, including those that are inactive or deleted, which are not eligible for connection to new connector objects.
https://github.com/eclipse-tractusx/portal-frontend/issues/929

fix(connector management): update api endpoint

---

src/assets/locales/en/main.json

fix typo in connector management overlay
bothers me, as the usability for the process isn't so great at least the explanation should not have typos
https://github.com/eclipse-tractusx/portal-frontend/issues/694
https://github.com/eclipse-tractusx/portal-frontend/pull/717

chore(connector overlay): fix typo

---

DEPENDENCIES
package.json
yarn.lock

Upgrade shared component library.
This is a regular process and third party libraries have been upgraded due to security findings.
n/a

chore(deps): upgrade shared components

---

CHANGELOG.md
src/components/pages/AppSubscription/ActivateSubscriptionOverlay/index.tsx
src/components/pages/AppSubscription/AppSubscriptionDetailOverlay/index.tsx
src/components/pages/AppSubscription/AppSubscriptionDetailOverlay/style.scss

implement loading state for provider subscription detail overlay
When accessing the provider subscription detail view and initiating the detail overlay, the UI currently pre-fills data fields with "n/a" before the backend has completed fetching the data. So, loader is needed
https://github.com/eclipse-tractusx/portal-frontend/issues/922

feat(subscription details): implement loader for subscription

---

src/assets/locales/de/main.json
src/assets/locales/en/main.json
src/components/pages/CompanyData/components/FormFields.tsx
src/types/Patterns.ts

update company data input patterns
should be in sync with registration repo
#894 

fix(company data): update company data input patterns

---

CHANGELOG.md
DEPENDENCIES
package.json
src/assets/locales/de/main.json
src/assets/locales/en/main.json
src/components/pages/TechnicalUserManagement/TechnicalUserTable.tsx
src/features/admin/serviceApiSlice.ts
yarn.lock

Enhance technical user table by adding StatusTag to the status column by fetching the status from the backend 
Enhance technical user table status column by adding new status 'pending deletion'
To enhance technical user table by adding StatusTag to the status column 
Technical user table status column is updated with new status 'pending deletion'
https://github.com/eclipse-tractusx/portal-frontend/issues/944, https://github.com/eclipse-tractusx/portal-frontend/issues/988

feat(technical user management): enhance table with status column

---

src/components/overlays/AppMarketplaceRequest/index.tsx
src/components/pages/AppDetail/components/AppDetailHeader/index.tsx
src/components/pages/AppMarketplace/components/AppListSection/index.tsx
src/features/overlay/slice.ts
src/features/store.ts

- I've to update the global store as we don't have any common state for the app details page and subscription dialog.
Added a slice which tell us if dialog is open/closed or is confirm button clicked.
- Globally, we can use this state to perform any action based on the dialog ex. if dialog is open/closed, or user confirms the action, we can perform any dependant action based on this.
- 
- App Marketplace : After requesting an app subscription, users need to perform a hard refresh of the page to view the updated status
- https://github.com/eclipse-tractusx/portal-frontend/issues/984

fix: change text of button when user requests subscription

---

CHANGELOG.md
src/components/pages/AdminBoardDetail/AdminBoardDetail.scss

- Specifically, the footer section overlaps with the service content, and the content extends beyond the footer section.
- The footer section overlaps with the service details page's service context.
- Page content has a fixed height that is creating an issue for the footer, I have removed that height, and working perfectly fine for now.
[Link to Github issue.
](https://github.com/eclipse-tractusx/portal-frontend/issues/995)

fix: Resolve height related displaying issue

---

src/components/overlays/ActivateServiceSubscription/index.tsx
src/features/serviceManagement/apiSlice.ts

- In the Service Subscriptions section, after activating a service, the user is redirected to a blank page.
- When we hit the Confirm button, we get multiple Technical Users in technicalUserInfo. Ideally, The frontend has to display various Technical Users. But, according to the current Implementation, we are expecting an object that is WRONG.
- Currently, We are showing multiple Technical Users in "Provider View" in the same way I show multiple Technical Users in the Confirmation Screen.
[Link to Github issue.
](https://github.com/eclipse-tractusx/portal-frontend/issues/1004)

fix: Resolve blank page issue after activating service subscription

---

src/components/pages/AppOverview/AppOverview.scss
src/components/pages/AppOverview/index.tsx
src/components/pages/AppOverviewNew/index.tsx
src/features/apps/apiSlice.ts
src/features/apps/types.ts

- Added Load more button in app overview
- Updated apiSlice fetchProvidedApps query to allow pagination 
- Added StatusIdEnum to handle pagination of different category views
load more button missing. Unable to expand list view to show available apps of all categories.  When the number apps exceeds 15, there is now possibility to see the rest. 
#1008

fix: add load more button app overview

---

CHANGELOG.md
DEPENDENCIES
src/assets/locales/de/main.json
src/assets/locales/en/main.json
src/components/pages/Admin/components/RegistrationRequests/CompanyDetailOverlay/CompanyDetailsHelper.tsx
src/components/pages/Admin/components/RegistrationRequests/RegistrationRequests.scss
src/components/pages/Admin/components/RegistrationRequests/components/CheckList/CheckListFullButtons.tsx
src/components/pages/Admin/components/RegistrationRequests/registrationTableColumns.tsx
src/components/pages/EdcConnector/edcConnectorTableColumns.tsx
src/components/shared/basic/Progress/index.tsx
src/features/admin/applicationRequestApiSlice.ts

update the status(skipped) in application requests and necessary changes with checkbox in connector management
Due to the implementation of a new status for the self description step we need to be able to show the status skipped in application requests and Connector SD Checkbox should be empty if connector status is skipped
https://github.com/eclipse-tractusx/portal-frontend/issues/948

feat(application requests and connector management): update skipped status

---

CHANGELOG.md
DEPENDENCIES
src/components/pages/TechnicalUserManagement/TechnicalUserTable.tsx
src/features/admin/serviceApiSlice.ts

Removed 'Inactive' filter in technical user management
NA
https://github.com/eclipse-tractusx/portal-frontend/issues/983

feat(technical user management): remove inactive filter

---

CHANGELOG.md
src/components/pages/EdcConnector/ConnectorDetailsOverlay.tsx
src/components/shared/basic/ReleaseProcess/OfferCard/index.tsx
src/features/connector/connectorApiSlice.ts

Updated SD document download API to fix downloading SD document issue
Also, fixed back button navigation to service management instead of navigating to home page
On clicking self description document, instead of downloading document, it throws error.
https://github.com/eclipse-tractusx/portal-frontend/issues/1037

fix(sd document): update SD document download API 

---

src/assets/locales/de/notification.json
src/assets/locales/en/notification.json

Renamed the translation key from `appsubscription` to `appSubscription` in the `notification.json` file to fix a key mismatch.
The text `link.appSubscription` is displayed because the key `appSubscription` does not exist in the translation file, as the current key is incorrectly named `appsubscription`.
[1053](https://github.com/eclipse-tractusx/portal-frontend/issues/1053)

fix: rename 'appsubscription' to 'appSubscription' in notification.json

---

CHANGELOG.md
src/components/overlays/ActivateServiceSubscription/index.tsx
src/features/serviceManagement/apiSlice.ts

update auto setup api response data in the service subscription response overlay
after autosetup api, website showing up a blank page
#1016 

fix(service subscription): update auto setup api response data

---

CHANGELOG.md
src/components/pages/AppDetail/components/AppDetailHeader/index.tsx
src/types/Constants.ts

- Add subscribe_apps constant
- Remove subscribe_service requirement for app subscription in app marketplace header component.
Partially relates to: eclipse-tractusx/portal-iam#173
Subscribing to apps should not require subscribe_service role.
Refs: eclipse-tractusx/portal-frontend#1012

feat(marketplace): Adjusted role requirement for app subscription

---

CHANGELOG.md
src/components/pages/AppReleaseProcess/index.tsx

- The "Overview My Apps" button is not working whenever the user clicks the button. It should be working like the Service Release Process and redirect to the respective page (App Overview Page)
- 'Overview my apps' button is not working on the App Release Process page.
[Link to Github issue.
](https://github.com/eclipse-tractusx/portal-frontend/issues/1022)

fix: Overview My App button not working on App Release Process page

---

CHANGELOG.md
src/components/overlays/DeleteTechnicalUser/index.tsx
src/components/pages/TechnicalUserManagement/index.tsx

show proper errors on page notification.
closing page notification bar issue.
broken error message on error scenario.
not able to close the page notification bar
#1034 

fix(tech user): error message and close notification bar

---

src/types/Constants.ts

Prevent users with the 'App Manager' role from accessing the Service Subscription Management page via the URL.
To maintain role-based access control and prevent unauthorized actions.
[991](https://github.com/eclipse-tractusx/portal-frontend/issues/991)

fix: update service subscription mgt page role

---

CHANGELOG.md
src/components/pages/OSPConsent/CompanyDetails.tsx

Company name in OSP form was hardcoded with "BMW"
Company name in OSP company details form should reflect the actual company
#1080 

fix: Display invited company name in OSP consent form

---

CHANGELOG.md
src/components/pages/CompanyData/components/CompanyAddressList.tsx

disable csv upload button in company data page
csv upload is not fully functional
after upload, sites/address are moving to INITIAL state

fix(company data): disable csv upload

---

src/assets/locales/de/main.json
src/assets/locales/en/main.json
src/components/overlays/EditPortalRoles/index.tsx
src/components/shared/basic/UserRoles/index.tsx

**GOAL:**
To ensure that a company can not block itself by removing all Adminroles from their enabled users.
**Option 1:**
We check how many users in the company have the respective admin role (e.g. CX Admin) and allow the removal only if there are >2 people with this specific role.
Otherwise, the role selector will be greyed out and the tooltip will explain the situation
**Option 2:**
We grey out all admin roles from a user if he goes into his role configuration.
Only if someone else would try to remove his role this would be possible.
This would at least ensure that someone is not removing his own role on fault but would include a 4-eye principle process.
Option 1 has a dependency on BE as we don't have an API that fetches all users of the company with roles.
So I've implemented the …

fix: block user from removing own admin roles

---

CHANGELOG.md
src/assets/locales/de/main.json
src/assets/locales/en/main.json
src/components/pages/EdcConnector/ConnectorDetailsOverlay.tsx
src/components/pages/EdcConnector/DeleteConfirmationOverlay/DeleteConfirmationOverlay.tsx
src/components/pages/EdcConnector/index.tsx
src/features/connector/connectorApiSlice.ts

- Updated the title text in overlay popup.
- Modified the logic for keeping the `confirm` delete button enabled in the delete confirmation overlay for the EDC connector.
- Adjusted the API call to include query parameters `deleteServiceAccount` based on checkbox selection
- Removed the delete connector button from the ConnectorManagement Detail overlay page anymore
- This change improves the functionality of connector deletion. 
- The user should be able to delete the connector without removing the technical user, but we still need to provide the option to delete both
#1065  

feat: modify delete connector user popup

---

src/components/pages/ServiceReleaseProcess/components/ServiceDetails.tsx
src/types/MainTypes.ts
src/utils/buff2hex.ts

- Added function to create image object url
- Added image type constants
- Buffer to hex conversion function
Upon opening any service detail, images set during service onboarding were not being displayed and only a static default image was being rendered for all services. due to missing/not yet present implementation. 
#990 

fix(service detail): add missing header image implementation 

---

src/assets/locales/de/main.json
src/assets/locales/en/main.json
src/components/pages/TechnicalUserManagement/TechnicalUserTable.tsx
src/features/admin/serviceApiSlice.ts

This PR introduces a new column named `Usertype` in the `technicalUserManagement` table. The column is positioned between `Type` (renamed to `Ownership`) and `Offer Link`.
**Key Changes:**
- Added the `Usertype` column to display the usertype value.
- Updated the `Type` column to `Ownership`.
- Ensured the layout remains responsive after the addition of the `Usertype` column.
- Ensured that the page gracefully handles missing or incorrect data without breaking functionality.
**Dependency:**
This change depends on the backend update to include the **`usertype`** field in the API response from **`GET: api/administration/serviceaccount/owncompany/serviceaccounts`**. The backend implementation for this feature is tracked under [sig#789 - API Expansion for Technical User Information …

feat: add Usertype column to technical user management list

---

CHANGELOG.md
src/assets/locales/de/main.json
src/assets/locales/en/main.json

DeleteConfirmationOverlay: Updated label text
- Inconsistent wording during connector deletion in checkbox label
#1097 

fix: updated the checkbox label text

---

CHANGELOG.md
src/assets/locales/de/main.json
src/assets/locales/de/servicerelease.json
src/assets/locales/en/main.json
src/assets/locales/en/servicerelease.json
src/components/shared/templates/Subscription/index.tsx

update search placeholder text.
show only available offer names at the top
wrong search place holder has been added.
show only available offers to filter
#1089 

fix(subscription management): updates on search place holder & offer filter buttons

---

CHANGELOG.md
src/components/pages/AdminBoardDetail/AdminBoardDetail.scss
src/components/styles/_breakpoints.scss

ServiceAdminBoardDetails page : 
- Resolved UI issue on the ServiceAdminBoardDetails page where long service titles caused layout distortion.
- Refined styling to ensure the page remains fully responsive across different screen sizes.
- To enhance the page's responsiveness and ensure a better user experience across devices.
#1107

fix(serviceAdminBoard): detail page responsiveness

---

DEPENDENCIES
package.json
src/components/overlays/OSPRegister/OSPRegisterContent.tsx
src/components/overlays/UpdateCertificate/index.tsx
src/components/pages/CompanyCertificates/UploadCompanyCerificate.tsx
src/components/shared/basic/ReleaseProcess/AppMarketCard/index.tsx
src/components/shared/basic/ReleaseProcess/TechnicalIntegration/index.tsx
src/components/shared/basic/ReleaseProcess/components/ConnectorFormInputField.tsx
src/components/shared/templates/StaticTemplateResponsive/Cards/RenderImage.tsx
src/features/companyCertification/companyCertificateApiSlice.tsx
yarn.lock

Fix type errors caused by type changes in shared components.
**Reference:**
- Removal of `any` type: [PR #312](https://github.com/eclipse-tractusx/portal-shared-components/pull/312)
- The shared components now use stricter types for improved type safety.
- Updating the code ensures consistency and prevents type-related issues with the shared components.
- Avoids runtime errors and ensures the app functions correctly after the shared component updates.
[1110](https://github.com/eclipse-tractusx/portal-frontend/issues/1110)

fix: update type issues caused by the removal of 'any' type in shared components

---

CHANGELOG.md
src/components/pages/OSPConsent/CompanyDetails.tsx

- Added filter function to only show pre-selected roles from OSP
User should not be able to select roles that were not pre-selected by the OSP
#1109

fix: filter out roles not defined by OSP

---

CHANGELOG.md
DEPENDENCIES
src/components/pages/EdcConnector/index.tsx

Fixed overlay enabling on click of managed connectors(details)
When user clicks on managed connectors(details), overlay should open to display further connector details
https://github.com/eclipse-tractusx/portal-frontend/issues/1014

fix(connector management): fix details overlay

---

CHANGELOG.md
DEPENDENCIES
src/components/pages/CompanyData/components/CompanyAddressList.tsx
src/components/pages/CompanyData/components/EditForm.tsx

enable csv upload in company data page and reverted manual intervention with ready state api introduced with https://github.com/eclipse-tractusx/portal-frontend/pull/958
enabled feature is needed for R24.12 and setting of ready state is now taken care of from BDPM side due to changed configuration
https://github.com/eclipse-tractusx/portal-frontend/issues/955

feat(company data): re-enable csv upload and revert setting of ready state

---

src/components/shared/frame/Header/index.tsx

don't show overlay for submitted application to operator
Unlike other companies, the operator company needs to be able to act within the Portal from the start independently from the application approval process, relates to https://github.com/eclipse-tractusx/portal-backend/issues/1003#issuecomment-2391717366
https://github.com/eclipse-tractusx/portal-frontend/issues/1203

feat: don't show overlay for submitted application to operator

---

src/components/overlays/AddTechnicalUser/TechnicalUserAddForm.scss

Fixed the issue where the technical role description was overlapping on small screens by adjusting the CSS to ensure proper text wrapping.
To prevent text from overlapping and ensure a clean, readable layout on smaller screens.
[1146](https://github.com/eclipse-tractusx/portal-frontend/issues/1146)

fix: display technical role description correctly on small screen

---

src/components/pages/TechnicalUserManagement/TechnicalUserTable.tsx

The following changes have been made:
- Adjusted the **column width** to ensure that the header text displays with an ellipsis (...) when necessary.
- Ensured that the **sort icon** remains visible and properly aligned next to the truncated text without any overlap.
- Tooltip functionality remains intact to display the full header text on hover.
The previous layout caused the sort icon to overlap with the column header, making both the text and the sort icon difficult to read and use. By adjusting the width and ensuring proper alignment, we maintain the clean and professional appearance of the UI while also improving the usability of the column sorting feature
[#1158](https://github.com/eclipse-tractusx/portal-frontend/issues/1158)

fix(technical user table): prevent overlap between text and sort icon

---

src/components/pages/Home/components/StageSection/index.tsx
src/components/shared/frame/SlidingMainHeader/Header.tsx
src/components/shared/frame/SlidingMainHeader/SlidingMainHeader.tsx

This PR addresses the issue where users without the required permissions could still see and click buttons in the home page slider, which would lead to **Unauthorized** pages. 
The following changes have been made:
- **Disabled buttons** in the slider (including **"My Apps"**) for users who do not have the necessary permissions.
- Ensured that these buttons remain visible but non-clickable for unauthorized users, providing a clear visual indicator that they do not have access.
- The change prevents the display of error pages when users attempt to click on restricted sections.
This change improves the user experience by preventing unauthorized access pages for users without permission.
[#1157](https://github.com/eclipse-tractusx/portal-frontend/issues/1157)

fix: disable My Apps button for users without permission

---

src/components/pages/NotificationCenter/Notifications.scss

Align search input color on the notification page with other portal pages for UI consistency.
To maintain consistent UI across the portal.
[#1169](https://github.com/eclipse-tractusx/portal-frontend/issues/1169)

fix: align notification page search field color with other pages

---

src/components/pages/Organization/MyCompanyInfoComponent.tsx

Fix text overlap issue in the Company Roles section on the My Company page
To ensure the text in the Company Roles section is readable and not overlapped.
#1172

fix(my company): fix text overlap issue at company roles

---

CHANGELOG.md
src/types/Config.tsx
src/types/Constants.ts

change  from read_partner to read_partner_member role from BPDM client 
https://github.com/eclipse-tractusx/portal-frontend/issues/1233

fix(partner network): change role to access page

---

src/assets/locales/de/main.json
src/assets/locales/en/main.json
src/components/shared/basic/KeyValueView/index.tsx
src/components/shared/basic/ReadOnlyValue/index.tsx

Display snackbar notification when user click on copy icon in the configure IDP overlay redirect URL and Technical user detail page 
To inform user with a notification when the content is copied
#1183

fix: add notification on copy action in technical user detail page

---

CHANGELOG.md
DEPENDENCIES
src/components/pages/OnboardingServiceProvider/OnboardingServiceProvider.tsx

- Remove hardcoded OSP callback url string and replace with OSP callback variable
The URL does not get updated with the current URL or does not update when being changed. Instead, a dummy URL is displayed. 
#1196

fix: replace OSP callback hardcode with variable

---

CHANGELOG.md
src/assets/locales/de/main.json
src/assets/locales/de/servicerelease.json
src/assets/locales/en/main.json
src/assets/locales/en/servicerelease.json

App and Service subscription search box translations doesn't work with DE so I introduced new translation keys for the search.
In order to get the correct translation for like the rest of the elements, I updated the translation file for the searchbox in App and Service subscription.
https://github.com/eclipse-tractusx/portal-frontend/issues/1210

fix(UI): app and service searchbox translation

---

CHANGELOG.md
src/components/pages/CompanySubscriptions/components/CompanySubscriptionTechnical/index.tsx

Change role and path for technical user details in companySubscriptionDetails.
- view_tech_user_management (instead of view_user_account)
- techUserDetails (instead of userdetails)
The section is showing a list of technical users instead of portal user. Links and roles do not fit the intended purpose.
Closes: eclipse-tractusx/portal-frontend#1219

fix(company subscriptions): wrong hyperlink and role in subscription details

---

CHANGELOG.md
src/components/shared/basic/ReleaseProcess/OfferTechnicalIntegration/index.tsx

- **Context:** Service Release Process -> Step 4: Technical Integration.
- **Change:** Added an `if` condition in `useEffect` to verify if the user has assigned roles. If no roles are found, the "None" option is automatically selected.
- **Issue:** The "None" option in the Technical Integration was not retaining its selection after submission.
- **Solution:** This fix ensures that the "None" option remains selected when the user revisits the "Technical Integration" step, providing a more consistent and user-friendly experience.
Github Issue: [#1161](https://github.com/eclipse-tractusx/portal-frontend/issues/1161)
https://github.com/user-attachments/assets/b6a2bbf1-b8f3-42d5-9a24-c902f74510d9

fix: retain "None" Selection for Technical Integration in Service Release

---

src/features/adminBoard/serviceAdminBoardApiSlice.ts

- In the Service Request Management section, clicking the 'Load More' button generates a 400 Bad Request error, preventing additional service requests from being loaded.
- A 400 Bad Request error is generated when attempting to load more service requests.
- Github Issue: https://github.com/eclipse-tractusx/portal-frontend/issues/1168
- Service Management | 400 Bad Request when Clicking 'Load More' Button [#1168](https://github.com/eclipse-tractusx/portal-frontend/issues/1168)

fix(service management): fix 400 issue when clicking 'Load More' button

---

CHANGELOG.md
src/components/pages/SemanticHub/ModelTable.tsx

Fixed semantic hub data on click of filters and on refresh icon
On click on filters and on click of refresh icon, the data should load correctly
https://github.com/eclipse-tractusx/portal-frontend/issues/1148

fix(semantic hub): fix filters

---

CHANGELOG.md
package.json

finalize version 2.3.0-RC1 by merge into main
https://github.com/eclipse-tractusx/portal/issues/465

build(2.3.0-rc1): bump version and update docs

---

CHANGELOG.md
DEPENDENCIES
src/assets/locales/de/main.json
src/assets/locales/en/main.json
src/components/shared/basic/Dropzone/index.tsx
src/types/Constants.ts

converted file size from Bytes to Mega-Byte of uploaded document for better UX.
```
- **File Upload**:
- changed error text of uploaded file from Byte to MB [#866](https://github.com/eclipse-tractusx/portal-frontend/pull/1185)
```
It is hard for user to understand long digits in Bytes and easier to read in mega byte size for better understanding and usually the size of the file either comes in KB or MB.
https://github.com/eclipse-tractusx/portal-frontend/issues/1184

fix(file upload): change error text of uploaded file from byte to mb

---

src/components/pages/EdcConnector/ConnectorDetailsOverlay.tsx

Error persists of not-permitted edit URL in Connector configuration UI on different overlay of Connector configuration.
```
- **Connector Management**
- Edit URL error message persists in Connector configuration [#1301](https://github.com/eclipse-tractusx/portal-frontend/issues/1301)
```
we didn't handle the case where we have to make error message state to false on Overlay close of first Overlay Modal before opening second overlay modal of Connector configuration.
https://github.com/eclipse-tractusx/portal-frontend/issues/1301

fix: connector url edit error message in detail overlay

---

CHANGELOG.md
DEPENDENCIES
src/assets/locales/de/main.json
src/assets/locales/en/main.json
src/components/overlays/AddTechnicalUser/TechnicalUserAddForm.tsx
src/components/overlays/AddTechnicalUser/index.tsx
src/features/admin/serviceApiSlice.ts

Enhanced technical user management creation page by role type
As a Frontend Developer, I need to update the technical user self-service creation UI to include:
- fields for technical user type
- fields for service endpoint so that operators can specify and view this information during user setup.
- clear separation of internal / external users
- logic adjustment to ensure that the simultaneous selection of internal users and external users is not possible
https://github.com/eclipse-tractusx/portal-frontend/issues/1077

feat(technical user management): enhance creation page by role type

---

CHANGELOG.md
DEPENDENCIES
src/components/shared/basic/ReleaseProcess/ContractAndConsent/index.tsx
src/components/shared/basic/ReleaseProcess/components/CommonContractAndConsent.tsx

fix wrong api is called in the registration process of an app
Correct api should be called for download documents in the registration process of an app to make it functional.
https://github.com/eclipse-tractusx/portal-frontend/issues/1226

fix(app registration process): wrong api calling to download documents

---

CHANGELOG.md
DEPENDENCIES
src/assets/locales/de/main.json
src/assets/locales/en/main.json
src/components/pages/AdminClearingHouseSD/AdminClearingHouseSD.scss
src/components/pages/AdminClearingHouseSD/AdminClearingHouseSDElements.tsx

Enhance Admin UI for managing SD document retriggering
To provide a better experience for the customer the page should be enhanced by the common design patterns.
https://github.com/eclipse-tractusx/portal-frontend/issues/1216

feat(clearinghouse self-description): enhance admin UI

---

CHANGELOG.md
src/assets/locales/de/main.json
src/assets/locales/en/main.json
src/components/overlays/AddTechnicalUser/TechnicalUserAddForm.scss
src/components/overlays/AddTechnicalUser/TechnicalUserAddForm.tsx

Enhanced UI of technical user management creation page
For better look and for better user experience to distinguish between internal & external technical user sections.
https://github.com/eclipse-tractusx/portal-frontend/issues/1077

feat(technical user management): enhanced UI of creation page

---

src/components/overlays/AddAppUserRoles/index.tsx

- Once the user/admin has completed the role assignment process, the system allows an admin to proceed to the role assignment section without selecting a user when revisiting the assignment screen. If no new user is chosen, the system defaults to previously selected users.
- The system should display an error message indicating a user must be selected for the role assignment if no new user is chosen.
- Or Admin can not process further if a user is not selected.
- https://github.com/eclipse-tractusx/portal-frontend/issues/1267
- Fixed: Prevented admins from proceeding with role assignment without selecting a user. [#1267](https://github.com/eclipse-tractusx/portal-frontend/issues/1267)

fix(user management): Prevent admins from proceeding further without user

---

src/components/pages/ServiceMarketplaceDetail/components/MarketplaceProvider/index.tsx
src/features/serviceMarketplace/serviceApiSlice.ts

The 'Provider Homepage' field should display the URL provided during the service creation process on the Service details page.
The 'Provider Homepage' field on the Service Details page is displayed as blank, even though a URL was added during the service creation process.
**Reference:** https://github.com/eclipse-tractusx/portal-backend/pull/1126/files
https://github.com/eclipse-tractusx/portal-frontend/issues/1326
- **Service Marketplace Detail**
- add providerUri in the provider details page [#1326](https://github.com/eclipse-tractusx/portal-frontend/issues/1326)

fix(service marketplace detail): add providerUri in the provider details page

---

CHANGELOG.md
src/assets/locales/de/servicerelease.json
src/assets/locales/en/servicerelease.json
src/components/pages/ServiceReleaseProcess/components/ServiceListOverview.tsx

I introduced new entry in the object for the `IN_REVIEW` status and its translation to make it visible in Service Overview Page.
```
- **Service Overview Inreview filter**:
- Introduced filter of in-review in service overview page [#1218](https://github.com/eclipse-tractusx/portal-frontend/pull/1218)
```
we also need this filter to see the services which are currently in-review like we see for `ACTIVE` and for `INACTIVE` status.
https://github.com/eclipse-tractusx/portal-frontend/issues/1217

fix: introduced inreview filter for in the service overview

---

src/components/pages/CertificateCredentials/CertificateElements.tsx
src/components/pages/CertificateCredentials/index.tsx

Added a default message on the Certificate Credentials page to inform users when no certificate data is available.
To display a default message when no certificate data is available.
#1319

fix: text message not shown when no data is available

---

CHANGELOG.md
src/components/pages/IDPManagement/IDPList.tsx

Fixed shared IdP to remove 'configure' option as its not viable
For Identity Provider with identityProviderTypeId SHARED the configure option and the according overlay should not be displayed because the SHARED IdP can't be configured.  Also, the user shouldn't be shown a option that's not viable
https://github.com/eclipse-tractusx/portal-frontend/issues/1350

fix(idp-config): fix shared IdP to remove configure option

---

CHANGELOG.md
src/components/pages/EdcConnector/ConnectorDetailsOverlay.tsx

Fixed URL update in connector details
```
- **Connector Management**
- fixed URL update in connector details [#1373](https://github.com/eclipse-tractusx/portal-frontend/pull/1373)
```
Updated URL is not reflecting in connector details page until page refresh
https://github.com/eclipse-tractusx/portal-frontend/issues/1366

fix(connector-management): fix URL update

---

CHANGELOG.md
src/components/pages/CompanyData/components/DetailsOverlay.tsx
src/components/pages/CompanyData/components/EditForm.tsx

show error message in edit company data overlay in error scenario
```
**Company Data**
- fixed displaying of error message in company data edit overlay screen [#1385] (https://github.com/eclipse-tractusx/portal-frontend/pull/1385)
```
Current behaviour does not show up what is the error in the edit overlay page. User has to close the overlay to have a relook on the error message in the company data page. So allow user to view the same error info in the edit page which helps him to fix the issues in the form
#1383 

fix(company data): show error message in edit company data overlay

---

CHANGELOG.md
src/components/shared/basic/Dropzone/index.tsx
src/components/shared/basic/ReleaseProcess/AppPage/index.tsx
src/components/shared/basic/ReleaseProcess/OfferPage/index.tsx
src/types/Constants.ts

previously handling the uploaded pdf documents with maximum size of 0.8 mb and now the allowed limit has increased to 5 mb.
```
- **File Upload**:
- increased size limit for uploaded documents to 5 mb [#1187](https://github.com/eclipse-tractusx/portal-frontend/pull/1187)
```
Files like Contract & concern, Agreements could have bigger sizes then 0.8 mb so suggested limit was 5mb.
https://github.com/eclipse-tractusx/portal-frontend/issues/1186

feat(file upload): increase size limit for uploaded documents

---

CHANGELOG.md
src/assets/locales/de/idp.json
src/assets/locales/en/idp.json
src/components/overlays/AddIDP/index.tsx
src/types/Patterns.test.ts
src/types/Patterns.ts

Updated regex for the allowed characters for displayName in idp creation. Previously we were not showing any error message against violation of regex. Updated regex and error translations bases on certain violation.
```
- **IdP Creation**
- added hint for invalid input of display name [#1264](https://github.com/eclipse-tractusx/portal-frontend/issues/1264)
```
To have better UX to let the user know what he is doing wrong and what is expected for displayName and what type of string value BE expects for displayName.
https://github.com/eclipse-tractusx/portal-frontend/issues/1264

fix: add hint for display name at idp creation

---

CHANGELOG.md
src/components/shared/frame/AppPermissions/index.tsx

resolved truncated chip button issue in the app permissions section
```
**User Management Details**
- fixed truncated chip button issue in the app permissions section [#1372] (https://github.com/eclipse-tractusx/portal-frontend/pull/1372)
```
permissions are truncated
#1358 

fix: resolve style issue on app permission chip button

---

src/components/pages/EdcConnector/AddConnectorOverlay/index.tsx

Confirm button is enabled Mandatory fields not being entered.
```
- **Connector Registration**:
- fixed confirm button is enabled mandatory fields not being entered [#1389](https://github.com/eclipse-tractusx/portal-frontend/pull/1389)
```
Confirm button should not be enabled Mandatory fields not being entered
https://github.com/eclipse-tractusx/portal-frontend/issues/1334

fix(Connector Registration): fix confirm button without mandatory fields

---

src/components/pages/EdcConnector/AddConnectorOverlay/components/ConnectorTypeSelection.tsx
src/components/shared/frame/Header/index.tsx
src/features/admin/userApiSlice.ts
src/types/Config.tsx

remove customised logic to check company role info in osp page and header component. use company role check in config file to allow user to navigate to osp page.
```
**OSP**
- removed customised logic to check company role info in osp page and header component. use company role check in config file to allow user to navigate to osp page.[#1390](https://github.com/eclipse-tractusx/portal-frontend/pull/1390)
```
remove custom check for company roles
#1108 

refactor(osp): use new company role check

---

src/components/shared/basic/ReleaseProcess/AppMarketCard/index.tsx
src/components/shared/basic/ReleaseProcess/AppPage/index.tsx
src/features/appManagement/types.ts
src/utils/fileUtils.ts

fix wrong api is called in the registration process of an app
```
- **App Registration Process**:
- fixed wrong api calling to download documents [#1386](https://github.com/eclipse-tractusx/portal-frontend/pull/1386)
```
Correct api should be called for download documents in the registration process of an app to make it functional.
https://github.com/eclipse-tractusx/portal-frontend/issues/1226

fix(app registration process): fix wrong api calling to download documents

---

src/components/pages/AppMarketplace/components/FavoriteSection/index.tsx

Fixed my favorites truncated images in app marketplace.
```
- **App Marketplace**:
- fixed my favorites truncated images in app marketplace [#1396](https://github.com/eclipse-tractusx/portal-frontend/pull/1396)
```
My favourites app images should not be truncated.
https://github.com/eclipse-tractusx/portal-frontend/issues/1395

fix(app marketplace): fix truncated images

---

src/components/shared/basic/ReleaseProcess/OfferCard/index.tsx
src/components/shared/basic/ReleaseProcess/OfferPage/index.tsx
src/features/serviceManagement/types.ts

fix wrong api is called in the service release process for all steps.
```
- **Service Release Process**:
- fixed wrong api calling to download documents for all steps [#1384](https://github.com/eclipse-tractusx/portal-frontend/pull/1384)
```
Correct api should be called for download documents in the service release process to make it functional.
https://github.com/eclipse-tractusx/portal-frontend/issues/1225

fix(service release process): fix download document

---

DEPENDENCIES
public/template_app_role_upload.csv
src/components/shared/basic/ReleaseProcess/TechnicalIntegration/index.tsx
src/features/appManagement/apiSlice.ts

Updated the CSV file parsing journey in order to extract the German language translations for User role's description in process of App creation.
```
- **App Access Management**
- Added support to fetch German language translation from CSV file template for app User role [#1288](https://github.com/eclipse-tractusx/portal-frontend/issues/1288)
```
we weren't handling the User Role's description in German language from CSV file template.
https://github.com/eclipse-tractusx/portal-frontend/issues/1288

fix: user role description translations in en/de

---

src/components/overlays/UpdateIDP/UpdateIDPContent.tsx
src/components/pages/OnboardingServiceProvider/OnboardingServiceProvider.tsx
src/components/pages/TechnicalUserDetails/TechnicalUserDetailsContent.tsx
src/components/shared/basic/KeyValueView/index.tsx

Removed Password type fields from OSP callback config and IDP config screen because requirement is to make them text based Input while Adding/Updating the configuration of either of them and also made Technical User detail screen protected for the sensitive information with masking and toggleable them by introducing an eye icon.
```
- **Changelog entry**
- Technical User | IDP config | OSP callback config
- Introduced Masking for Sensitive information in Technical User Detail Section [#1399](https://github.com/eclipse-tractusx/portal-frontend/issues/1399)
```
Best Practice to hide the sensitive information by default and whenever Customer support team wants to prepare Demo video of Portal they says sensitive information should be hidden e.g., Passwords, secrets from Technical User Detail. …

fix: masked confidentail technical user fields

---

src/assets/locales/de/main.json
src/assets/locales/en/main.json
src/components/shared/basic/ReleaseProcess/OfferTechnicalIntegration/index.tsx
src/components/shared/basic/ReleaseProcess/TechnicalIntegration/AddTechUserForm.tsx
src/components/shared/basic/ReleaseProcess/TechnicalIntegration/TechUserTable.tsx
src/components/shared/basic/ReleaseProcess/TechnicalIntegration/index.tsx
src/components/shared/basic/ReleaseProcess/TechnicalIntegration/style.scss

enhance user experience by providing table and overlay in add technical user flow. List current users in the table. Allow user to edit the list in an overlay implementation
**Technical Integration - App and Service Release Process**
- enhance user experience by providing table and overlay in add technical user flow. list current users in the table. allow user to edit the list in an overlay implementation [#1401]
provide better user experience
#1125  #1305 

fix(app release process): enhance add technical user process

---

src/assets/locales/de/idp.json
src/assets/locales/de/main.json
src/assets/locales/de/servicerelease.json
src/assets/locales/en/idp.json
src/assets/locales/en/main.json

Unused translations for locales files are removed and missing translations are added.
Changelog:
- **Locales**
- unused translations for locales files are removed and missing translations are added [#1421](https://github.com/eclipse-tractusx/portal-frontend/pull/1421)
Unused translations for locales files to be removed and missing translations to be added
https://github.com/eclipse-tractusx/portal-frontend/issues/1419

feat(locales): update translations files

---

src/components/pages/EdcConnector/ConnectorDetailsOverlay.tsx
src/components/pages/EdcConnector/index.tsx

Fixed table connector URL update after updating and closing the overlay
- **Connector Management**
- fixed table connector URL update after updating and closing the overlay [#1420](https://github.com/eclipse-tractusx/portal-frontend/pull/1420)
Connector URL should update in table after its value is updated in details overlay.
https://github.com/eclipse-tractusx/portal-frontend/issues/1418

fix(connector management): fix connector URL update

---

src/components/pages/AppSubscription/ActivateSubscriptionOverlay/index.tsx

Fixed closing of overlay on click of close icon.
- **App Subscription**
- fixed closing of overlay on click of close icon [#1413](https://github.com/eclipse-tractusx/portal-frontend/pull/1413)
Close icon was not closing the overlay
https://github.com/eclipse-tractusx/portal-frontend/issues/1359

fix(app subscription): fix overlay close

---

CHANGELOG.md
src/components/shared/frame/UserList/index.tsx

- Added filter to role column renderCell on "User Management" screen user list to remove roles not associated with portal roles.
- The user list table on the "User Management" screen is showing roles for each user that are not related to portal access. For example, roles associated with app access. 
#1391

fix: remove non portal roles from user list

---

src/components/shared/basic/KeyValueView/index.tsx

Fix dom where div appears as a child of p
According to the HTML specification the p element must only contain "Phrasing Content" while div is not permitted: https://html.spec.whatwg.org/multipage/grouping-content.html#the-p-element
(Typography is rendered to p and StatusTag rendered to a div)
#1269 

fix(react): fix dom nesting

---

src/assets/locales/de/main.json
src/assets/locales/en/main.json

Improve partner network page copywriting
Avoid confusion linked to phrase "CX Member", which can also refers to Association members.
Use "Active Participant" instead.
https://github.com/eclipse-tractusx/portal-frontend/issues/1429

fix(copywriting): improve partner network page copywriting

---

src/components/pages/EdcConnector/EdcConnectorTableColumns.tsx

Fixed connector URL alignment in connector management page.
**Connector Management**
- Fixed connector URL alignment in connector management page. [#1461](https://github.com/eclipse-tractusx/portal-frontend/pull/1461)
Connector URL not aligned properly in connector management page.
https://github.com/eclipse-tractusx/portal-frontend/issues/1460

fix(connector management): fix url alignment

---

src/assets/locales/de/main.json
src/assets/locales/en/main.json
src/components/pages/AdminCredential/AdminCredentialElements.tsx
src/components/pages/AdminCredential/style.scss

disabled the document download icon for credential request's that doesn't have document attached.
we have had the check there to disable the download functionality and disabled the button but It needed to be fixed.
Now the button should be displayed as disabled and won't work. more over tool tip has been added for disabled icons.
https://github.com/eclipse-tractusx/portal-frontend/issues/1447

fix: disable document download button for unavailable documents

---

src/assets/locales/de/main.json
src/assets/locales/en/main.json
src/components/pages/AppOverview/AppOverViewDetails.tsx
src/components/shared/basic/ReleaseProcess/OfferTechnicalIntegration/index.tsx
src/components/shared/basic/ReleaseProcess/OfferValidateAndPublish/index.tsx
src/components/shared/basic/ReleaseProcess/TechnicalIntegration/AddTechUserForm.tsx
src/components/shared/basic/ReleaseProcess/TechnicalIntegration/TechUserTable.tsx
src/components/shared/basic/ReleaseProcess/TechnicalIntegration/index.tsx
src/components/shared/basic/ReleaseProcess/ValidateAndPublish/index.tsx
src/components/shared/basic/ReleaseProcess/components/CommonValidateAndPublish.tsx
src/features/appManagement/apiSlice.ts
src/features/appManagement/types.ts
src/features/serviceManagement/apiSlice.ts

use existing new user interface for creating multiple technical users in technical integration page.
Include edit/update feature.
Also support delete functionality.
```
**Technical Integration**
- enabled multiple tech user creation feature in technical integration step in app and service release process [#1441](https://github.com/eclipse-tractusx/portal-frontend/pull/1441)
```
NA
#1305 

fix(technical integration): enable multiple technical user creation 

---

CHANGELOG.md
src/components/pages/IDPManagement/IDPList.tsx

- Added value getter to column 
The filter of the status column('enabled field') was filtering based on the field 'enabled' which was a boolean value. The value we are setting within the cell however, is using a combination or two different fields to set variable values, resulting in the filter function of the component not able to filter based on the correct value. 
- **IdP Management**
- fixed IdP table status filter to sort by alphabetical order [#1443](https://github.com/eclipse-tractusx/portal-frontend/pull/1443)
#1442

fix: filter column based on cell value

---

src/assets/locales/de/main.json
src/assets/locales/de/servicerelease.json
src/assets/locales/en/main.json
src/assets/locales/en/servicerelease.json
src/components/shared/basic/ReleaseProcess/OfferTechnicalIntegration/index.tsx
src/components/shared/basic/ReleaseProcess/TechnicalIntegration/DeleteTechnicalUserProfileOverlay.tsx
src/components/shared/basic/ReleaseProcess/TechnicalIntegration/TechUserTable.tsx
src/components/shared/basic/ReleaseProcess/TechnicalIntegration/index.tsx

The deletion of a profile should enable a popup that asked if user really wants to delete.
To provide a better option to display multiple roles.
Technical Integration
Small Improvements in the technical user profile setup of app/service https://github.com/eclipse-tractusx/portal-frontend/pull/1472
The deletion of a profile does not warn the user. a popup that asked if he really wants to delete it would be handy.
There should be a better option to display multiple roles. as the height of the column is fixed we cant enhance it dynamically.
https://github.com/eclipse-tractusx/portal-frontend/issues/1444

feat(technical integration): technical user profile improvements

---

src/assets/locales/de/main.json
src/assets/locales/en/main.json
src/components/shared/basic/ReleaseProcess/ReleaseProcessSteps.scss
src/components/shared/basic/ReleaseProcess/TechnicalIntegration/AddTechUserForm.tsx
src/components/shared/basic/ReleaseProcess/TechnicalIntegration/TechUserTable.tsx
src/features/appManagement/types.ts
src/features/serviceManagement/apiSlice.ts

enhance tech user table in technical integration page with an eye icon which displays visibility info for the current row.
update add new technical form with grouping logic on internal tech user section.
add visibility icon to the technical user profile selection
[Link to Github issue.](https://github.com/eclipse-tractusx/portal-frontend/issues/1445)

fix: enhance user visibility experience

---

src/assets/locales/en/main.json
src/components/shared/basic/ReleaseProcess/TechnicalIntegration/AddTechUserForm.tsx

Fixed checkbox select/deselect for internal roles.
Technical integration
Fixed checkbox select/deselect for internal roles. https://github.com/eclipse-tractusx/portal-frontend/pull/1480
Checkbox selection was displaying wrongly
https://github.com/eclipse-tractusx/portal-frontend/issues/1445

fix(technical integration): fixed checkbox selection

---

src/components/shared/basic/ReleaseProcess/TechnicalIntegration/AddTechUserForm.tsx

add visibility icon to add tech user profile form in the radio button title.
new request
NA

fix: add visibility icon to internal/external section 

---

src/components/pages/AppDetail/AppDetailHeader/index.tsx
src/components/pages/ServiceMarketplaceDetail/MarketplaceHeader/index.tsx

fix unnecessary 400 issue in the app overlay
App Details Overlay
- App agreement data api being called with empty id. If the prop value which is passed to the component is empty, user app info to get the id value.
400 error is showing up on clicking subscribe button
#1483 

fix: use prop value if params appId is not defined

---

src/index.tsx
src/services/CompanyService.ts

company service init function to handle error callback 
Registration process
- handle error case in company service init method to avoid blank screen display. display error boundary component instead
When I try to login to the portal with as a user of a not yet onboarded company (still in registration phase), I'm greeted with a blank page due to not (yet) being allowed to view ownComanyDetails provided via backend api.
#1487 

fix: company service error handling

---

src/components/pages/AppDetail/AppDetailTechUserSetup/index.tsx
src/components/pages/ServiceMarketplaceDetail/MarketplaceTechnicalUserSetup/index.tsx
src/components/shared/basic/ReleaseProcess/TechnicalIntegration/TechUserTable.tsx

update tech user info component in app/service details page which is available from market place section
app/service using old component
NA

fix: use newly created tech user table in app/service detail page

---

src/components/pages/PartnerNetwork/index.tsx

do not show any result in the partner network table for empty search string
Partner Network
- do not allow to execute search feature for empty string
Partner network search allows to search for empty string
#1496 

fix: do not show search results for empty search

---

src/components/pages/CompanyData/CompanyAddressList.tsx

console error is leading to empty screen on creating new data in company data page. add a check and fix the issue to render updated data in the table
```
**Company data**
- add check for sharing state data to resolve empty page issue [#1511](https://github.com/eclipse-tractusx/portal-frontend/pull/1511)
```
create site/address leads empty page
#1497 

fix: handle js error on creating new company site/address

---

src/components/pages/ServiceReleaseProcess/ServiceOverview/ServiceDetails.tsx
src/components/pages/ServiceReleaseProcess/ServiceReleaseProcessForm/style.scss

Fixed service details page to display technical user setup in Service Overview
```
- **Service overview**:
- fixed service details page to display technical user setup in Service Overview. [#1508](https://github.com/eclipse-tractusx/portal-frontend/pull/1508)
```
Since technical user setup was not displaying in service details page in Service Overview
https://github.com/eclipse-tractusx/portal-frontend/issues/1504

fix(service overview): fix technical user setup display

---

src/components/overlays/AddIDP/index.tsx
src/components/pages/IDPManagement/IDPList.tsx

Full name not displaying on identity provider configuration page.
Also, updated validation for 'Display name' as per api response in IdP configuration.
```
- **Identity Provider Configuration**:
- fixed displaying of full name with tooltip on hover and updated validation for 'Display name' as per API response in IdP configuration. [#1502](https://github.com/eclipse-tractusx/portal-frontend/pull/1502)
```
Validation does not match with API response
https://github.com/eclipse-tractusx/portal-frontend/issues/1397

fix(idp): fix display name issue

---

src/components/shared/basic/ReleaseProcess/TechnicalIntegration/AddTechUserForm.tsx

Fixed validation of continue button to enable/disable while adding technical user profile
```
- **Technical Integration**:
- fixed validation of continue button to enable/disable while adding technical user profile. [#1513](https://github.com/eclipse-tractusx/portal-frontend/pull/1513)
```
Getting 400 error when clicking continue button without selecting any role for technical user profile.
https://github.com/eclipse-tractusx/portal-frontend/issues/1501

fix(technical integration): fix enable/disable continue button 

---

src/components/pages/CompanyWallet/RuleCard.tsx
src/types/Constants.ts

enable revocation of owned company credentials by introducing revoke_credential role.
```
- **Company Wallet**
- enabled - Company, Business and IT - admin roles to revoke own company credentials
```
owned company credentials could only be revoked by the CX Admin role
https://github.com/eclipse-tractusx/portal-frontend/issues/1521

fix: enable revocation of own company credentials

---

src/assets/locales/de/main.json
src/assets/locales/de/servicerelease.json
src/types/Constants.ts

Fixed service marketplace filters when the language is set to german.
Also updated german translations.
```
- **Service Marketplace**:
- Fixed filters when the language is set to german and also updated german translation for `Dataspace Services`  [#1531](https://github.com/eclipse-tractusx/portal-frontend/pull/1531)
```
In the Service Marketplace, the filter for services based on 'Service Type' is not working when the language is set to german (DE). Also, german translations are not updated.
https://github.com/eclipse-tractusx/portal-frontend/issues/1208

fix(service marketplace): fix filters and translations

---

src/components/pages/CompanySubscriptions/CompanySubscriptionDetail.tsx
src/components/pages/CompanySubscriptions/index.tsx

Clicking Back button on Service Company Subscription page Returns to App Company Subscription
```
- **Company Subscription**:
- fixed back button on details page returns on wrong tab. [#1532](https://github.com/eclipse-tractusx/portal-frontend/pull/1532)
```
Clicking Back button on Service Company Subscription page should be in on the same page.
https://github.com/eclipse-tractusx/portal-frontend/issues/1367

fix(company subscription): fix back button returns on wrong tab

---

src/assets/locales/de/main.json
src/assets/locales/en/main.json
src/components/pages/Organization/UnSubscribeOverlay.tsx

Added legal disclaimer that clicking on unsubscribe does not override T&Cs.
As well as updated copywriting and design as per UX requirements.
```
* **Unsubscribe overlay**
* updated legal disclaimer text as well as copywriting and design as per UX requirements [#1498](https://github.com/eclipse-tractusx/portal-frontend/pull/1498)
```
Users of portal should be aware of the implications of their unsubscribe action in portal. In particular that an unsubscribe in portal does not override their contractually agreed T&Cs.
none

feat: update unsubscribe overlay

---

src/assets/locales/de/main.json
src/assets/locales/en/main.json
src/components/shared/frame/UserList/index.tsx

Fixed app roles display in user list table in app user management. Also, updated dummy boilerplate text to accurate description.
```
- **User management**:
- fixed app roles display in user list table in app user management. Also, updated dummy boilerplate text to accurate description. [#1546](https://github.com/eclipse-tractusx/portal-frontend/pull/1546)
```
App roles are not displayed in user list table in app user management.
In menu screen "Assign app roles to your user(s)" a dummy boilerplate text is shown, not an accurate description of what is expected. So, replaced with accurate text/description.
https://github.com/eclipse-tractusx/portal-frontend/issues/1516

fix(user management): fix  app roles display

---

src/components/pages/EdcConnector/AddConnectorOverlay/ConnectorInsertForm.tsx
src/features/admin/serviceApiSlice.ts

Filter out the technical user which is not linked to any connector or offer in Connector registration
```
- **Connector registration**:
- added logic to show only available tech user. [#1570](https://github.com/eclipse-tractusx/portal-backend/issues/1570)
```
Previously it was allowing same technical user or technical user of offer to be linked with more than one connector
#1547 
eclipse-tractusx/portal-backend#1139

feat(connector): only show available tech user

---

src/assets/locales/de/main.json
src/assets/locales/en/main.json
src/components/pages/EdcConnector/EdcManagedConnectorTableColumns.tsx
src/components/pages/EdcConnector/edcProvidedConnectorTableColumns.tsx
src/components/pages/EdcConnector/index.tsx
src/features/connector/connectorApiSlice.ts

Added a new tab for Provided Connector, which will show the connector list provided by the logged-in company to their customer.
```
- **Connector registration**:
- Added a new tab for provided connector. [#1087](https://github.com/eclipse-tractusx/portal-backend/issues/1087)
```
There was no view where the provider could see the connectors that were provided to their customer. With this new view, they can manage the connector provided to their customer.
eclipse-tractusx/portal-backend#1087

feat(Connector): added a view for provided connector

---

DEPENDENCIES
package.json
yarn.lock

Integrate Catena-X shared components version update of 4.0.0 -> 4.0.1.
Dependency updates are now included.
eclipse-tractusx/portal-frontend#1560

feat: upgrade catena-x shared components to 4.0.1

---

src/assets/locales/de/main.json
src/assets/locales/en/main.json
src/components/overlays/AddServiceProvider/index.tsx
src/components/overlays/AddServiceProvider/style.scss
src/components/shared/basic/Input/ValidatingInput.tsx
src/features/serviceProvider/serviceProviderApiSlice.ts

Added auth fields in Auto setup 
```
- **app subscription management**:
- Added fields for auth in auto setup. [#1457](https://github.com/eclipse-tractusx/portal-frontend/pull/1457)
```
All customer have to share same authentication details for auto setup from central idp.
Now Company can save their own authentication details for auto setup url
[#1151](https://github.com/eclipse-tractusx/portal-backend/issues/1151)
NOTE: Please only merge it after this PR is merged [PR-1232](https://github.com/eclipse-tractusx/portal-backend/pull/1232)

feat(auto-setup): add fields for auth in auto setup

---

src/components/overlays/UpdateIDP/UpdateIDPContent.tsx

Added missing variable meta url value set on load. 
Meta url variable was being set to empty on load, causing the "Save Metadata" button to remain disabled as the meta url was being treated as empty even though it display correctly in the form. 
```
IDP management 
- Fix disabled Save Metadata button [1604](https://github.com/eclipse-tractusx/portal-frontend/pull/1604)
```
https://github.com/eclipse-tractusx/portal-frontend/issues/1595

fix: correctly disable Save Metadata button on invalid

---

src/components/pages/TechnicalUserManagement/style.scss
src/components/styles/main.scss

The Table column (in this case technicaluser management)  columns were stagnated because of hard coded max-width value. Now, with the resolution the width technically shouldn't be of fixed value rather dynamic so I make the max-width to 100% - adaptive.
```
- **Technical User**:
- Make Technical User table to span to full available width [1602](https://github.com/eclipse-tractusx/portal-frontend/pull/1602)
```
The value for the section was of 1200px in which we are rendering Table component that was the reason of column stagnation
https://github.com/eclipse-tractusx/portal-frontend/issues/1596

fix: sectioner contain width changed to auto-100%

---

CHANGELOG.md
src/components/pages/EdcConnector/AddConnectorOverlay/index.tsx

Once the technical user is assigned to any OWN connector then it the same technical user shouldn't be allowed to assigned to any other OWN connector until the connector gets deleted and user gets released.One technical user can only be assigned to one connector one at a time!
```
- **Connector Registration**:
- Fetch updated technical user list for new connector [1612](https://github.com/eclipse-tractusx/portal-frontend/pull/1612)
```
we weren't fetching the fresh list of technical user after an assignment to connector and hence were missing the new updated list of technical user.
https://github.com/eclipse-tractusx/portal-frontend/issues/1601

fix: pull fresh technical user - own connector

---

src/components/pages/CompanySubscriptions/index.tsx

- Adjusted MUI table row center align logic
The previous logic to center align row cell components does not work on every browser. Browsers such a Firefox and Chrome were not center aligning the cells where as Safari does. 
```
Company Subscription 
- Center align row cells with multi-browser friendly logic [1611](https://github.com/eclipse-tractusx/portal-frontend/pull/1611)
```
[1598](https://github.com/eclipse-tractusx/portal-frontend/issues/1598)
**Steps to reproduce**
- Open up to portal in Chrome & Firefox browsers
- Login as a company admin
- Navigate to the Company subscriptions page

fix: adjust row cell logic to work on all browsers

---

src/components/overlays/AddAppUserRoles/AppRoles.tsx

App has the roles for access and and only granted user will be able to access the app who has the right/role to access it!
Due to some adopted practice the role selection wasn't happening for apps!
```
- **User Management | App Access Management**:
- persist user selection on navigating back from role selection [#1603](https://github.com/eclipse-tractusx/portal-frontend/pull/1603)
```
We were calling the hook inside the function which is not allowed to do so just moved the selector based hook out the function body to inside the main function body and it works!
https://github.com/eclipse-tractusx/portal-frontend/issues/1597

fix: user role selection for app access

---

src/components/pages/AdminBoardDetail/BoardTechnicalUserSetup/index.tsx
src/components/pages/ServiceAdminBoardDetail/index.tsx

- Added logging to join all objects with an array to display all available user profiles for both app and service admin details.
- Only the first index of the user profile array was being displayed, although there can be one or multiple.
```
App & Service admin detail board
- Add missing user technical profiles on admin detail board [1615](https://github.com/eclipse-tractusx/portal-frontend/pull/1615)
```
#1613
#1614

fix: add missing user technical profiles

---

DEPENDENCIES
yarn.lock

Remove axios library from yarn.lock and update DEPENDENCIES file.
PR [#1525](https://github.com/eclipse-tractusx/portal-frontend/pull/1525) did not removed axios library from yarn.lock even though it is not in use anymore.
Caused by: [#1525](https://github.com/eclipse-tractusx/portal-frontend/pull/1525)

chore(cleanup): remove unused axios library from yarn.lock

---

src/features/appManagement/apiSlice.ts
src/features/appSubscription/appSubscriptionApiSlice.ts
src/features/serviceManagement/apiSlice.ts

🚧 Updated the naming conventions used in App/Service release process api's.Turned naming convention to Pascal case format for consistency. 
As a standard practice we should remain consistent with the naming convention used project wide.
https://github.com/eclipse-tractusx/portal-frontend/issues/1587

fix: align app/service release endpoint naming

---

src/assets/locales/de/main.json
src/assets/locales/de/servicerelease.json
src/assets/locales/en/main.json
src/assets/locales/en/servicerelease.json
src/components/pages/AppSubscription/DeclineSubscriptionOverlay/index.tsx
src/components/pages/AppSubscription/DeclineSubscriptionOverlay/style.scss
src/components/pages/AppSubscription/index.tsx
src/components/pages/ServiceSubscription/index.tsx
src/components/shared/cfx/generic.ts
src/components/shared/templates/Subscription/SubscriptionElements.tsx
src/components/shared/templates/Subscription/index.tsx
src/components/shared/templates/Subscription/style.scss
src/features/admin/serviceApiSlice.ts
src/features/appSubscription/appSubscriptionApiSlice.ts
src/features/serviceManagement/apiSlice.ts
src/features/serviceMarketplace/serviceApiSlice.ts
src/features/serviceSubscription/serviceSubscriptionApiSlice.ts

We have apps and service’s subscriptions which we want to “Decline” by App/Service Provider or Admin type of users. Currently we only have Activate and Deactivate Subscription functionality by App/Service Provider type of users.
- Frontend would still be looking at the isSubscribed param from api/apps/{appId} API to make decisions upon showing different statuses of subscription on App Details Page
- Frontend would need to show another button as “Decline“ on App/Service Subscription page only when "offerSubscriptionStatus": "PENDING" in /api/Apps/provided/subscription-status API.
- Frontend may show a confirmation box to user and then call this new API, when user confirm.
- Frontend would have to refresh the list after the declination. …

feat(App/Service Subscription): Ability to Decline the Subscription requests
